-- Date: 2015-7
-- File: msg_cg_beauty.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义用户群芳阁协议
--// 协议号分配：20800 ~ 20899


QueryBeautyInfoReqBody = {
    ["name"] = "QueryBeautyInfoReqBody",
    ["id"] = 20800,
}

QueryBeautyInfoRespBody = {
    ["name"] = "QueryBeautyInfoRespBody",
    ["id"] = 20801,
    ["attribs"] = {
        {"beautyInfos", "BeautyInfo", "repeat"},
        {"beautyGroups", "BeautyGroup", "repeat"},
        {"timeLeft", "uint32"},
        {"countLeft", "uint32"},
    },
}

KissReqBody = {
    ["name"] = "KissReqBody",
    ["id"] = 20802,
    ["attribs"] = {
        {"id", "uint32"},
    },
}

KissRespBody = {
    ["name"] = "KissRespBody",
    ["id"] = 20803,
    ["attribs"] = {
        {"beautyInfo", "BeautyInfo"},
        {"roleAttr", "RoleAttrInfo", "repeat"},
        {"timeLeft", "uint32"},
        {"countLeft", "uint32"},
    },
}

BeautyAwakeReqBody = {
    ["name"] = "BeautyAwakeReqBody",
    ["id"] = 20804,
    ["attribs"] = {
        {"groupId", "uint32"},
        {"index", "uint32"},
    },
}

BeautyAwakeRespBody = {
    ["name"] = "BeautyAwakeRespBody",
    ["id"] = 20805,
    ["attribs"] = {
        {"roleAttr", "RoleAttrInfo", "repeat"},
    },
}

