-- Date: 2015-10
-- File: msg_cg_night.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义用户午夜惊魂相关协议
--// 协议号分配：21800 ~ 21899


UseUnDeadReqBody = {
    ["name"] = "UseUnDeadReqBody",
    ["id"] = 21800,
}

UseUnDeadRespBody = {
    ["name"] = "UseUnDeadRespBody",
    ["id"] = 21801,
}

AnswerRightReqBody = {
    ["name"] = "AnswerRightReqBody",
    ["id"] = 21802,
}

AnswerRightRespBody = {
    ["name"] = "AnswerRightRespBody",
    ["id"] = 21803,
}

