-- Date: 2015-10
-- File: msg_cg_arena.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义用户技能系统协议
--// 协议号分配：21600 ~ 21699


QueryArenaInfoReqBody = {
    ["name"] = "QueryArenaInfoReqBody",
    ["id"] = 21600,
}

QueryArenaInfoRespBody = {
    ["name"] = "QueryArenaInfoRespBody",
    ["id"] = 21601,
    ["attribs"] = {
        {"pageInfo", "ArenaPageInfo"},
        {"roleList", "RoleArenaInfo", "repeat"},
    },
}

FightReqBody = {
    ["name"] = "FightReqBody",
    ["id"] = 21602,
    ["attribs"] = {
        {"roleId", "uint32"},
    },
}

FightRespBody = {
    ["name"] = "FightRespBody",
    ["id"] = 21603,
    ["attribs"] = {
        {"roleInfo", "RoleFightInfo"},
    },
}

FightResultReqBody = {
    ["name"] = "FightResultReqBody",
    ["id"] = 21604,
    ["attribs"] = {
        {"isWin", "bool"},
    },
}

FightResultRespBody = {
    ["name"] = "FightResultRespBody",
    ["id"] = 21605,
    ["attribs"] = {
        {"currRank", "uint32"},
        {"items", "ItemInfo", "repeat"},
        {"finances", "FinanceUnit", "repeat"},
    },
}

QueryArenaRankReqBody = {
    ["name"] = "QueryArenaRankReqBody",
    ["id"] = 21606,
    ["attribs"] = {
        {"beginPos", "uint32"},
        {"endPos", "uint32"},
    },
}

QueryArenaRankRespBody = {
    ["name"] = "QueryArenaRankRespBody",
    ["id"] = 21607,
    ["attribs"] = {
        {"roleList", "RoleArenaInfo", "repeat"},
    },
}

RefreshEnemyReqBody = {
    ["name"] = "RefreshEnemyReqBody",
    ["id"] = 21608,
}

RefreshEnemyRespBody = {
    ["name"] = "RefreshEnemyRespBody",
    ["id"] = 21609,
    ["attribs"] = {
        {"roleList", "RoleArenaInfo", "repeat"},
    },
}

DrawArenaBoxReqBody = {
    ["name"] = "DrawArenaBoxReqBody",
    ["id"] = 21610,
}

DrawArenaBoxRespBody = {
    ["name"] = "DrawArenaBoxRespBody",
    ["id"] = 21611,
    ["attribs"] = {
        {"boxCount", "uint32"},
        {"remainTime", "uint32"},
        {"awardInfo", "AwardInfo"},
    },
}

