-- Date: 2015-10
-- File: msg_cg_shop.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义用户背包物品协议
--// 协议号分配：20500 ~ 20599


QueryShopInfoReqBody = {
    ["name"] = "QueryShopInfoReqBody",
    ["id"] = 20500,
    ["attribs"] = {
        {"shopType", "uint16"},
    },
}

QueryShopInfoRespBody = {
    ["name"] = "QueryShopInfoRespBody",
    ["id"] = 20501,
    ["attribs"] = {
        {"tags", "ShopTag", "repeat"},
        {"goods", "GoodsInfo", "repeat"},
    },
}

QueryGoodsListReqBody = {
    ["name"] = "QueryGoodsListReqBody",
    ["id"] = 20502,
    ["attribs"] = {
        {"shopType", "uint16"},
        {"tagId", "uint16"},
    },
}

QueryGoodsListRespBody = {
    ["name"] = "QueryGoodsListRespBody",
    ["id"] = 20503,
    ["attribs"] = {
        {"goods", "GoodsInfo", "repeat"},
    },
}

BuyGoodsReqBody = {
    ["name"] = "BuyGoodsReqBody",
    ["id"] = 20504,
    ["attribs"] = {
        {"shopType", "uint16"},
        {"goodsId", "uint32"},
        {"count", "uint32"},
    },
}

BuyGoodsRespBody = {
    ["name"] = "BuyGoodsRespBody",
    ["id"] = 20505,
    ["attribs"] = {
        {"currentGoods", "GoodsInfo"},
    },
}

QueryChargeListReqBody = {
    ["name"] = "QueryChargeListReqBody",
    ["id"] = 20506,
}

QueryChargeListRespBody = {
    ["name"] = "QueryChargeListRespBody",
    ["id"] = 20507,
    ["attribs"] = {
        {"chargeLists", "ChargeItem", "repeat"},
    },
}

GainVipBoxReqBody = {
    ["name"] = "GainVipBoxReqBody",
    ["id"] = 20508,
    ["attribs"] = {
        {"vipLevel", "uint32"},
    },
}

GainVipBoxRespBody = {
    ["name"] = "GainVipBoxRespBody",
    ["id"] = 20509,
}

GenerateOrderReqBody = {
    ["name"] = "GenerateOrderReqBody",
    ["id"] = 20510,
    ["attribs"] = {
        {"channelId", "uint32"},
        {"rechargeId", "uint32"},
    },
}

GenerateOrderRespBody = {
    ["name"] = "GenerateOrderRespBody",
    ["id"] = 20511,
    ["attribs"] = {
        {"extraData", "string"},
        {"productId", "string"},
    },
}

