-- Date: 2015-10
-- File: msg_cg_huashan.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义用户华山论剑相关协议
--// 协议号分配：21900 ~ 21999


QueryHSInfoReqBody = {
    ["name"] = "QueryHSInfoReqBody",
    ["id"] = 21900,
}

QueryHSInfoRespBody = {
    ["name"] = "QueryHSInfoRespBody",
    ["id"] = 21901,
    ["attribs"] = {
        {"buffLevel", "uint32"},
        {"enemys", "HuaShanRoleInfo", "repeat"},
    },
}

QueryHSEnemyDetailReqBody = {
    ["name"] = "QueryHSEnemyDetailReqBody",
    ["id"] = 21902,
    ["attribs"] = {
        {"rank", "uint32"},
    },
}

QueryHSEnemyDetailRespBody = {
    ["name"] = "QueryHSEnemyDetailRespBody",
    ["id"] = 21903,
    ["attribs"] = {
        {"roleInfo", "RoleFightInfo"},
    },
}

FightHSEnemyReqBody = {
    ["name"] = "FightHSEnemyReqBody",
    ["id"] = 21904,
    ["attribs"] = {
        {"rank", "uint32"},
    },
}

FightHSEnemyRespBody = {
    ["name"] = "FightHSEnemyRespBody",
    ["id"] = 21905,
    ["attribs"] = {
        {"roleInfo", "RoleFightInfo"},
    },
}

FightHSResultReqBody = {
    ["name"] = "FightHSResultReqBody",
    ["id"] = 21906,
    ["attribs"] = {
        {"isWin", "bool"},
    },
}

FightHSResultRespBody = {
    ["name"] = "FightHSResultRespBody",
    ["id"] = 21907,
    ["attribs"] = {
        {"award", "AwardInfo"},
    },
}

AddHSBuffReqBody = {
    ["name"] = "AddHSBuffReqBody",
    ["id"] = 21908,
    ["attribs"] = {
        {"isDiamond", "bool"},
    },
}

AddHSBuffRespBody = {
    ["name"] = "AddHSBuffRespBody",
    ["id"] = 21909,
    ["attribs"] = {
        {"buffLevel", "uint32"},
    },
}

