-- Date: 2015-10
-- File: msg_cg_mail.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义用户邮件相关协议
--// 协议号分配：22200 ~ 22299


GetMailsReqBody = {
    ["name"] = "GetMailsReqBody",
    ["id"] = 22200,
}

GetMailsRespBody = {
    ["name"] = "GetMailsRespBody",
    ["id"] = 22201,
    ["attribs"] = {
        {"mailList", "MailDemo", "repeat"},
    },
}

GetMailInfoReqBody = {
    ["name"] = "GetMailInfoReqBody",
    ["id"] = 22202,
    ["attribs"] = {
        {"index", "uint32"},
    },
}

GetMailInfoRespBody = {
    ["name"] = "GetMailInfoRespBody",
    ["id"] = 22203,
    ["attribs"] = {
        {"info", "MailInfo"},
    },
}

DeleteMailReqBody = {
    ["name"] = "DeleteMailReqBody",
    ["id"] = 22204,
    ["attribs"] = {
        {"index", "uint32", "repeat"},
    },
}

DeleteMailRespBody = {
    ["name"] = "DeleteMailRespBody",
    ["id"] = 22205,
}

GetGoodsReqBody = {
    ["name"] = "GetGoodsReqBody",
    ["id"] = 22206,
    ["attribs"] = {
        {"index", "uint32", "repeat"},
    },
}

GetGoodsRespBody = {
    ["name"] = "GetGoodsRespBody",
    ["id"] = 22207,
}

