-- Date: 2015-10
-- File: msg_cg_pet.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义宠物系统协议
--// 协议号分配：21500 ~ 21599


GetPetsReqBody = {
    ["name"] = "GetPetsReqBody",
    ["id"] = 21500,
}

GetPetsRespBody = {
    ["name"] = "GetPetsRespBody",
    ["id"] = 21501,
    ["attribs"] = {
        {"petInfos", "PetInfo", "repeat"},
        {"fieldIds", "uint32", "repeat"},
    },
}

FieldReqBody = {
    ["name"] = "FieldReqBody",
    ["id"] = 21502,
    ["attribs"] = {
        {"petId", "uint32"},
    },
}

FieldRespBody = {
    ["name"] = "FieldRespBody",
    ["id"] = 21503,
    ["attribs"] = {
        {"fieldIds", "uint32", "repeat"},
        {"roleInfo", "RoleAttrInfo"},
    },
}

UnFieldReqBody = {
    ["name"] = "UnFieldReqBody",
    ["id"] = 21504,
    ["attribs"] = {
        {"petId", "uint32"},
    },
}

UnFieldRespBody = {
    ["name"] = "UnFieldRespBody",
    ["id"] = 21505,
    ["attribs"] = {
        {"fieldIds", "uint32", "repeat"},
        {"roleInfo", "RoleAttrInfo"},
    },
}

CompoundReqBody = {
    ["name"] = "CompoundReqBody",
    ["id"] = 21506,
    ["attribs"] = {
        {"chipId", "uint32"},
    },
}

CompoundRespBody = {
    ["name"] = "CompoundRespBody",
    ["id"] = 21507,
    ["attribs"] = {
        {"petInfos", "PetInfo", "repeat"},
    },
}

AdvanceReqBody = {
    ["name"] = "AdvanceReqBody",
    ["id"] = 21508,
    ["attribs"] = {
        {"petId", "uint32"},
    },
}

AdvanceRespBody = {
    ["name"] = "AdvanceRespBody",
    ["id"] = 21509,
    ["attribs"] = {
        {"step", "uint32"},
        {"roleInfo", "RoleAttrInfo"},
    },
}

FeedReqBody = {
    ["name"] = "FeedReqBody",
    ["id"] = 21510,
    ["attribs"] = {
        {"petId", "uint32"},
        {"materialId", "uint32"},
    },
}

FeedRespBody = {
    ["name"] = "FeedRespBody",
    ["id"] = 21511,
    ["attribs"] = {
        {"petInfo", "PetInfo"},
        {"roleInfo", "RoleAttrInfo"},
    },
}

