-- Date: 2015-10
-- File: msg_xx_global.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义一些公司平台级别全局常量


--// 定义公司内部各应用的ID
kAppIdType = {
    APPID_UNKNOWN = 0,
    APPID_MISSION = 1,  --// 使命
}

--// 定义公司内部接入的平台(渠道)ID
--// 本公司也算作平台(渠道)的一种
kPlatformType = {
    PFT_UNKNOWN = 0,
    PFT_CHINAFILM = 1,  --// 中影内部渠道
}

--// 分区状态枚举
kZoneStateType = {
    SST_UNKONWN = 0,  --// 未知
    SST_NORMAL = 1,  --// 普通
    SST_HOT = 2,  --// 火爆
    SST_STOP = 3,  --// 维护
}

--// 分区类型枚举
kZoneType = {
    ZT_UNKONWN = 0,  --// 未知
    ZT_NEW = 1,  --// 新区
    ZT_RECOMMEND = 2,  --// 推荐
}

DeviceInfo = {
    ["name"] = "DeviceInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"device_id", "string"},
        {"locale", "string"},
        {"language", "string"},
        {"model", "string"},
        {"os", "string"},
        {"width_pixels", "uint32"},
        {"high_pixels", "uint32"},
        {"idfa", "string"},
        {"ip", "string"},
        {"mac", "string"},
        {"ext", "string"},
    },
}

AppVersionInfo = {
    ["name"] = "AppVersionInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"app_id", "uint16"},
        {"platform", "uint16"},
        {"major_version", "uint16"},
        {"minor_version", "uint16"},
        {"version_info", "string"},
    },
}

ServerInfo = {
    ["name"] = "ServerInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"zoneStatus", "uint16"},
        {"zoneType", "uint16"},
        {"zoneId", "uint32"},
        {"zoneName", "string"},
        {"ipAddr", "string"},
        {"port", "uint16"},
    },
}

