-- Date: 2015-8
-- File: msg_cg_blade.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义用户剑灵系统协议
--// 协议号分配：20700 ~ 20799


QueryBladeSoulReqBody = {
    ["name"] = "QueryBladeSoulReqBody",
    ["id"] = 20700,
}

QueryBladeSoulRespBody = {
    ["name"] = "QueryBladeSoulRespBody",
    ["id"] = 20701,
    ["attribs"] = {
        {"roleAttrExt", "RoleAttrInfo"},
        {"refineList", "RefineUnit", "repeat"},
        {"baldeSoulList", "BladeSoul", "repeat"},
    },
}

RefineItemReqBody = {
    ["name"] = "RefineItemReqBody",
    ["id"] = 20702,
    ["attribs"] = {
        {"index", "uint32"},
    },
}

RefineItemRespBody = {
    ["name"] = "RefineItemRespBody",
    ["id"] = 20703,
    ["attribs"] = {
        {"refineList", "RefineUnit", "repeat"},
    },
}

CollectBladeSoulReqBody = {
    ["name"] = "CollectBladeSoulReqBody",
    ["id"] = 20704,
    ["attribs"] = {
        {"index", "uint32"},
    },
}

CollectBladeSoulRespBody = {
    ["name"] = "CollectBladeSoulRespBody",
    ["id"] = 20705,
    ["attribs"] = {
        {"baldeSole", "BladeSoul"},
        {"refineList", "RefineUnit", "repeat"},
    },
}

CancelRefineReqBody = {
    ["name"] = "CancelRefineReqBody",
    ["id"] = 20706,
    ["attribs"] = {
        {"index", "uint32"},
    },
}

CancelRefineRespBody = {
    ["name"] = "CancelRefineRespBody",
    ["id"] = 20707,
    ["attribs"] = {
        {"refineList", "RefineUnit", "repeat"},
    },
}

BoostRefineReqBody = {
    ["name"] = "BoostRefineReqBody",
    ["id"] = 20708,
    ["attribs"] = {
        {"index", "uint32"},
    },
}

BoostRefineRespBody = {
    ["name"] = "BoostRefineRespBody",
    ["id"] = 20709,
    ["attribs"] = {
        {"baldeSole", "BladeSoul"},
        {"refineList", "RefineUnit", "repeat"},
    },
}

DevourBladeSoulReqBody = {
    ["name"] = "DevourBladeSoulReqBody",
    ["id"] = 20710,
    ["attribs"] = {
        {"index", "uint32"},
    },
}

DevourBladeSoulRespBody = {
    ["name"] = "DevourBladeSoulRespBody",
    ["id"] = 20711,
    ["attribs"] = {
        {"roleAttr", "RoleAttrInfo"},
        {"addRoleAttr", "RoleAttrInfo"},
    },
}

SellBladeSoulReqBody = {
    ["name"] = "SellBladeSoulReqBody",
    ["id"] = 20712,
    ["attribs"] = {
        {"index", "uint32"},
    },
}

SellBladeSoulRespBody = {
    ["name"] = "SellBladeSoulRespBody",
    ["id"] = 20713,
}

AutoRefineItemReqBody = {
    ["name"] = "AutoRefineItemReqBody",
    ["id"] = 20714,
    ["attribs"] = {
        {"indexs", "uint32", "repeat"},
    },
}

AutoRefineItemRespBody = {
    ["name"] = "AutoRefineItemRespBody",
    ["id"] = 20715,
    ["attribs"] = {
        {"refineList", "RefineUnit", "repeat"},
    },
}

AutoDevourBladeSoulReqBody = {
    ["name"] = "AutoDevourBladeSoulReqBody",
    ["id"] = 20716,
}

AutoDevourBladeSoulRespBody = {
    ["name"] = "AutoDevourBladeSoulRespBody",
    ["id"] = 20717,
    ["attribs"] = {
        {"roleAttr", "RoleAttrInfo"},
        {"addRoleAttr", "RoleAttrInfo"},
    },
}

