-- Date: 2015-9
-- File: msg_cg_cjg.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与藏经阁间的部分协议
--// 定义藏经阁协议
--// 协议号分配：22400-22499


GetLibraryInfoReqBody = {
    ["name"] = "GetLibraryInfoReqBody",
    ["id"] = 22400,
}

GetLibraryInfoRespBody = {
    ["name"] = "GetLibraryInfoRespBody",
    ["id"] = 22401,
    ["attribs"] = {
        {"bibleList", "BookInfo", "repeat"},
    },
}

InsertPageReqBody = {
    ["name"] = "InsertPageReqBody",
    ["id"] = 22402,
    ["attribs"] = {
        {"bookId", "uint32"},
        {"pageIndex", "uint32"},
    },
}

InsertPageRespBody = {
    ["name"] = "InsertPageRespBody",
    ["id"] = 22403,
}

