-- Date: 2015-10
-- File: msg_cg_cjg.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 瀹氫箟浜嗗鎴风涓庤棌缁忛榿闂寸殑閮ㄥ垎鍗忚
--// 瀹氫箟钘忕粡闃佸崗璁?
--// 鍗忚鍙峰垎閰嶏細22400-22499


GetLibraryInfoReqBody = {
    ["name"] = "GetLibraryInfoReqBody",
    ["id"] = 22400,
}

GetLibraryInfoRespBody = {
    ["name"] = "GetLibraryInfoRespBody",
    ["id"] = 22401,
    ["attribs"] = {
        {"bibleList", "BookInfo", "repeat"},
    },
}

InsertPageReqBody = {
    ["name"] = "InsertPageReqBody",
    ["id"] = 22402,
    ["attribs"] = {
        {"bookId", "uint32"},
        {"pageIndex", "uint32"},
    },
}

InsertPageRespBody = {
    ["name"] = "InsertPageRespBody",
    ["id"] = 22403,
}

