-- Date: 2015-10
-- File: msg_cg_item.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义用户背包物品协议
--// 协议号分配：20100 ~ 20499


QueryPackageListReqBody = {
    ["name"] = "QueryPackageListReqBody",
    ["id"] = 20100,
}

QueryPackageListRespBody = {
    ["name"] = "QueryPackageListRespBody",
    ["id"] = 20101,
    ["attribs"] = {
        {"openCount", "uint32"},
        {"itemList", "ItemInfo", "repeat"},
    },
}

OpenPackageCellReqBody = {
    ["name"] = "OpenPackageCellReqBody",
    ["id"] = 20102,
}

OpenPackageCellRespBody = {
    ["name"] = "OpenPackageCellRespBody",
    ["id"] = 20103,
    ["attribs"] = {
        {"tootle", "uint32"},
    },
}

TidyPackageReqBody = {
    ["name"] = "TidyPackageReqBody",
    ["id"] = 20104,
}

TidyPackageRespBody = {
    ["name"] = "TidyPackageRespBody",
    ["id"] = 20105,
    ["attribs"] = {
        {"itemList", "ItemInfo", "repeat"},
    },
}

WearEquipmentReqBody = {
    ["name"] = "WearEquipmentReqBody",
    ["id"] = 20106,
    ["attribs"] = {
        {"index", "uint32"},
    },
}

WearEquipmentRespBody = {
    ["name"] = "WearEquipmentRespBody",
    ["id"] = 20107,
    ["attribs"] = {
        {"roleInfo", "RoleDetailInfo"},
        {"itemList", "ItemInfo", "repeat"},
    },
}

TakeoffEquipmentReqBody = {
    ["name"] = "TakeoffEquipmentReqBody",
    ["id"] = 20108,
    ["attribs"] = {
        {"location", "uint16"},
    },
}

TakeoffEquipmentRespBody = {
    ["name"] = "TakeoffEquipmentRespBody",
    ["id"] = 20109,
    ["attribs"] = {
        {"roleInfo", "RoleDetailInfo"},
        {"itemList", "ItemInfo", "repeat"},
    },
}

SetFashionOptReqBody = {
    ["name"] = "SetFashionOptReqBody",
    ["id"] = 20110,
    ["attribs"] = {
        {"loction", "uint16"},
        {"optionValue", "bool"},
    },
}

SetFashionOptRespBody = {
    ["name"] = "SetFashionOptRespBody",
    ["id"] = 20111,
}

ResolveEquipReqBody = {
    ["name"] = "ResolveEquipReqBody",
    ["id"] = 20112,
    ["attribs"] = {
        {"indexes", "uint32", "repeat"},
    },
}

ResolveEquipRespBody = {
    ["name"] = "ResolveEquipRespBody",
    ["id"] = 20113,
}

StoneSynthesisReqBody = {
    ["name"] = "StoneSynthesisReqBody",
    ["id"] = 20114,
    ["attribs"] = {
        {"stoneId", "uint32"},
    },
}

StoneSynthesisRespBody = {
    ["name"] = "StoneSynthesisRespBody",
    ["id"] = 20115,
}

BagEqpStoneSynthesisReqBody = {
    ["name"] = "BagEqpStoneSynthesisReqBody",
    ["id"] = 20116,
    ["attribs"] = {
        {"index", "uint32"},
        {"stoneId", "uint32"},
    },
}

BagEqpStoneSynthesisRespBody = {
    ["name"] = "BagEqpStoneSynthesisRespBody",
    ["id"] = 20117,
}

RoleEqpStoneSynthesisReqBody = {
    ["name"] = "RoleEqpStoneSynthesisReqBody",
    ["id"] = 20118,
    ["attribs"] = {
        {"loction", "uint16"},
        {"stoneId", "uint32"},
    },
}

RoleEqpStoneSynthesisRespBody = {
    ["name"] = "RoleEqpStoneSynthesisRespBody",
    ["id"] = 20119,
    ["attribs"] = {
        {"roleInfo", "RoleDetailInfo"},
    },
}

InlayBagEquipReqBody = {
    ["name"] = "InlayBagEquipReqBody",
    ["id"] = 20120,
    ["attribs"] = {
        {"opposite", "bool"},
        {"eqpIndex", "uint32"},
        {"stoneId", "uint32"},
        {"stoneIndex", "uint32"},
    },
}

InlayBagEquipRespBody = {
    ["name"] = "InlayBagEquipRespBody",
    ["id"] = 20121,
}

InlayRoleEquipReqBody = {
    ["name"] = "InlayRoleEquipReqBody",
    ["id"] = 20122,
    ["attribs"] = {
        {"opposite", "bool"},
        {"loction", "uint16"},
        {"stoneId", "uint32"},
        {"stoneIndex", "uint32"},
    },
}

InlayRoleEquipRespBody = {
    ["name"] = "InlayRoleEquipRespBody",
    ["id"] = 20123,
    ["attribs"] = {
        {"roleInfo", "RoleDetailInfo"},
    },
}

IntensifyBagEquipReqBody = {
    ["name"] = "IntensifyBagEquipReqBody",
    ["id"] = 20124,
    ["attribs"] = {
        {"auto", "bool"},
        {"index", "uint32"},
    },
}

IntensifyBagEquipRespBody = {
    ["name"] = "IntensifyBagEquipRespBody",
    ["id"] = 20125,
    ["attribs"] = {
        {"equipHistory", "ItemInfo", "repeat"},
    },
}

IntensifyRoleEquipReqBody = {
    ["name"] = "IntensifyRoleEquipReqBody",
    ["id"] = 20126,
    ["attribs"] = {
        {"auto", "bool"},
        {"location", "uint16"},
    },
}

IntensifyRoleEquipRespBody = {
    ["name"] = "IntensifyRoleEquipRespBody",
    ["id"] = 20127,
    ["attribs"] = {
        {"roleInfo", "RoleDetailInfo"},
        {"fightingHistory", "uint32", "repeat"},
    },
}

SellItemReqBody = {
    ["name"] = "SellItemReqBody",
    ["id"] = 20128,
    ["attribs"] = {
        {"index", "uint32"},
        {"count", "uint32"},
    },
}

SellItemRespBody = {
    ["name"] = "SellItemRespBody",
    ["id"] = 20129,
}

ForgingEquipReqBody = {
    ["name"] = "ForgingEquipReqBody",
    ["id"] = 20130,
    ["attribs"] = {
        {"chipId", "uint32"},
        {"mapId", "uint32"},
    },
}

ForgingEquipRespBody = {
    ["name"] = "ForgingEquipRespBody",
    ["id"] = 20131,
    ["attribs"] = {
        {"proItemList", "ItemInfo", "repeat"},
    },
}

OpenBoxReqBody = {
    ["name"] = "OpenBoxReqBody",
    ["id"] = 20132,
    ["attribs"] = {
        {"index", "uint32"},
        {"count", "uint32"},
    },
}

OpenBoxRespBody = {
    ["name"] = "OpenBoxRespBody",
    ["id"] = 20133,
    ["attribs"] = {
        {"finances", "FinanceUnit", "repeat"},
        {"beautyList", "BeautyInfo", "repeat"},
        {"items", "ItemInfo", "repeat"},
    },
}

EatPillsReqBody = {
    ["name"] = "EatPillsReqBody",
    ["id"] = 20134,
    ["attribs"] = {
        {"index", "uint32"},
        {"count", "uint32"},
    },
}

EatPillsRespBody = {
    ["name"] = "EatPillsRespBody",
    ["id"] = 20135,
    ["attribs"] = {
        {"exp", "uint32"},
        {"level", "uint32"},
        {"strength", "uint32"},
    },
}

SellCheapItemReqBody = {
    ["name"] = "SellCheapItemReqBody",
    ["id"] = 20136,
}

SellCheapItemRespBody = {
    ["name"] = "SellCheapItemRespBody",
    ["id"] = 20137,
}

