-- Date: 2015-7
-- File: msg_cg_skill.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义用户技能系统协议
--// 协议号分配：21400 ~ 21499


QuerySkillListReqBody = {
    ["name"] = "QuerySkillListReqBody",
    ["id"] = 21400,
}

QuerySkillListRespBody = {
    ["name"] = "QuerySkillListRespBody",
    ["id"] = 21401,
    ["attribs"] = {
        {"actvSkills", "SkillUnit", "repeat"},
        {"pasvSkills", "SkillUnit", "repeat"},
        {"consSkills", "SkillUnit", "repeat"},
        {"mountSkills", "SkillUnit", "repeat"},
    },
}

UpgradeSkillReqBody = {
    ["name"] = "UpgradeSkillReqBody",
    ["id"] = 21402,
    ["attribs"] = {
        {"skillId", "uint32"},
    },
}

UpgradeSkillRespBody = {
    ["name"] = "UpgradeSkillRespBody",
    ["id"] = 21403,
    ["attribs"] = {
        {"skillInfo", "SkillUnit"},
        {"roleAttr", "RoleAttrInfo", "repeat"},
    },
}

MountSkillReqBody = {
    ["name"] = "MountSkillReqBody",
    ["id"] = 21404,
    ["attribs"] = {
        {"skillId", "uint32"},
    },
}

MountSkillRespBody = {
    ["name"] = "MountSkillRespBody",
    ["id"] = 21405,
    ["attribs"] = {
        {"fightingPower", "uint32"},
        {"roleSkills", "SkillUnit", "repeat"},
    },
}

