-- Date: 2015-10
-- File: msg_gd_common.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define


GD_AttrInfo = {
    ["name"] = "GD_AttrInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"attrType", "uint16"},
        {"attrValue", "double"},
    },
}

GD_FinanceInfo = {
    ["name"] = "GD_FinanceInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"finance", "uint16"},
        {"amount", "uint32"},
    },
}

GD_AddBattle = {
    ["name"] = "GD_AddBattle",
    ["id"] = 0,
    ["attribs"] = {
        {"copyId", "uint32"},
        {"copyTp", "uint16"},
        {"buyCount", "uint16"},
    },
}

GD_VipData = {
    ["name"] = "GD_VipData",
    ["id"] = 0,
    ["attribs"] = {
        {"level", "uint32"},
        {"totalRecharge", "uint32"},
        {"gainBoxes", "uint32"},
        {"addStrength", "uint32"},
        {"addBattle", "GD_AddBattle", "repeat"},
    },
}

GD_AccountData = {
    ["name"] = "GD_AccountData",
    ["id"] = 0,
    ["attribs"] = {
        {"channel", "uint16"},
        {"deviceId", "string"},
        {"createIp", "string"},
        {"loginIp", "string"},
    },
}

GD_RoleAttrInfo = {
    ["name"] = "GD_RoleAttrInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"hp", "uint32"},
        {"attack", "uint32"},
        {"defend", "uint32"},
        {"critRate", "uint32"},
        {"critDmage", "uint32"},
        {"resilience", "uint32"},
        {"resistance", "uint32"},
        {"block", "uint32"},
        {"penetration", "uint32"},
        {"dodgeRate", "uint32"},
        {"attrEnhanced", "uint32"},
        {"fireAttack", "uint32"},
        {"coldAttack", "uint32"},
        {"lightningAttack", "uint32"},
        {"lifePerSecond", "uint32"},
        {"lifeSteal", "uint32"},
    },
}

GD_EqpExtInfo = {
    ["name"] = "GD_EqpExtInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"majorAttr", "GD_AttrInfo"},
        {"minorAttr", "GD_AttrInfo", "repeat"},
        {"stoneId", "uint32", "repeat"},
    },
}

GD_ItemInfo = {
    ["name"] = "GD_ItemInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"id", "uint32"},
        {"value", "uint32"},
        {"position", "uint32"},
        {"equipment", "GD_EqpExtInfo", "repeat"},
    },
}

GD_RoleInfo = {
    ["name"] = "GD_RoleInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"roleId", "uint32"},
        {"userId", "uint32"},
        {"exp", "uint32"},
        {"level", "uint32"},
        {"gold", "uint32"},
        {"dimaond", "uint32"},
        {"strength", "uint32"},
        {"contribution", "uint32"},
        {"realmPoint", "uint32"},
        {"soulPoint", "uint32"},
        {"fightingPower", "uint32"},
        {"reviveCount", "uint32"},
        {"newerPro", "string"},
        {"type", "uint16"},
        {"roleName", "string"},
        {"creatTime", "uint32"},
        {"lastLoginTime", "uint32"},
        {"lastTrigger", "uint32"},
        {"lastStrength", "uint32"},
        {"fashionOption", "uint16"},
        {"quipment", "GD_ItemInfo", "repeat"},
        {"vipData", "GD_VipData"},
        {"accountData", "GD_AccountData"},
    },
}

GD_RoleSimpleInfo = {
    ["name"] = "GD_RoleSimpleInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"roleId", "uint32"},
        {"userId", "uint32"},
        {"type", "uint16"},
        {"roleName", "string"},
    },
}

GD_FairyPillInfo = {
    ["name"] = "GD_FairyPillInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"id", "uint32"},
        {"level", "uint32"},
        {"exp", "uint32"},
        {"index", "uint32"},
    },
}

GD_FairyDishInfo = {
    ["name"] = "GD_FairyDishInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"exp", "uint32"},
        {"level", "uint32"},
        {"holes", "GD_FairyPillInfo", "repeat"},
        {"package", "GD_FairyPillInfo", "repeat"},
    },
}

GD_BladeSoul = {
    ["name"] = "GD_BladeSoul",
    ["id"] = 0,
    ["attribs"] = {
        {"id", "uint32"},
        {"attrbs", "GD_AttrInfo", "repeat"},
    },
}

GD_RefineUnit = {
    ["name"] = "GD_RefineUnit",
    ["id"] = 0,
    ["attribs"] = {
        {"id", "uint32"},
        {"state", "uint16"},
        {"begin_time", "uint32"},
        {"soul", "GD_BladeSoul"},
    },
}

GD_BeautyInfo = {
    ["name"] = "GD_BeautyInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"id", "uint32"},
        {"num", "uint32"},
        {"exp", "uint32"},
    },
}

GD_BeautyGroupInfo = {
    ["name"] = "GD_BeautyGroupInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"id", "uint32"},
        {"memebers", "bool", "repeat"},
    },
}

GD_BeautyHouseInfo = {
    ["name"] = "GD_BeautyHouseInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"lastTime", "uint32"},
        {"kissNum", "uint32"},
        {"allBeauty", "GD_BeautyInfo", "repeat"},
        {"allGroup", "GD_BeautyGroupInfo", "repeat"},
    },
}

GD_SkillInfo = {
    ["name"] = "GD_SkillInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"skillId", "uint32"},
        {"level", "uint32"},
        {"isMount", "bool"},
    },
}

GD_BattleUnit = {
    ["name"] = "GD_BattleUnit",
    ["id"] = 0,
    ["attribs"] = {
        {"battleId", "uint32"},
        {"count", "uint32"},
        {"star", "uint32"},
    },
}

GD_StoryInfo = {
    ["name"] = "GD_StoryInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"lastBattle", "uint32"},
        {"storyInfos", "StoryUnit", "repeat"},
    },
    ["StoryUnit"] = {
        ["name"] = "StoryUnit",
        ["attribs"] = {
            {"storyId", "uint32"},
            {"draw", "bool", "repeat"},
        },
    },
}

GD_TowerInfo = {
    ["name"] = "GD_TowerInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"towerInfos", "TowerUnit", "repeat"},
    },
    ["TowerUnit"] = {
        ["name"] = "TowerUnit",
        ["attribs"] = {
            {"towerId", "uint32"},
            {"copyId", "uint32"},
            {"fightCount", "uint32"},
        },
    },
}

GD_BattleInfo = {
    ["name"] = "GD_BattleInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"battles", "GD_BattleUnit", "repeat"},
        {"storyExtInfo", "GD_StoryInfo"},
        {"towerExtInfo", "GD_TowerInfo"},
    },
}

GD_PetInfo = {
    ["name"] = "GD_PetInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"id", "uint32"},
        {"level", "uint32"},
        {"step", "uint32"},
        {"exp", "uint32"},
    },
}

GD_ArenaInfo = {
    ["name"] = "GD_ArenaInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"rank", "uint32"},
        {"gainReward", "uint32"},
        {"lastGain", "uint32"},
        {"boxCount", "uint32"},
        {"refreshCount", "uint32"},
        {"winStreak", "uint32"},
        {"fightCount", "uint32"},
    },
}

GD_TaskInfo = {
    ["name"] = "GD_TaskInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"taskId", "uint32"},
        {"progress", "uint32"},
        {"status", "uint32"},
        {"context", "string"},
    },
}

GD_VitalityInfo = {
    ["name"] = "GD_VitalityInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"vitality", "uint32"},
        {"boxState", "bool", "repeat"},
    },
}

GD_MidNightInfo = {
    ["name"] = "GD_MidNightInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"lastEntryTime", "uint32"},
        {"entryCount", "uint32"},
    },
}

GD_HSInfo = {
    ["name"] = "GD_HSInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"koCount", "uint32"},
        {"buffLevel", "uint32"},
    },
}

GD_BuffInfo = {
    ["name"] = "GD_BuffInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"id", "uint32"},
        {"birthday", "uint32"},
    },
}

GD_AwardInfo = {
    ["name"] = "GD_AwardInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"items", "GD_ItemInfo", "repeat"},
        {"finances", "GD_FinanceInfo", "repeat"},
    },
}

GD_MailInfo = {
    ["name"] = "GD_MailInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"index", "uint32"},
        {"id", "uint32"},
        {"isRead", "bool"},
        {"hasGot", "bool"},
        {"date", "uint32"},
        {"args", "string", "repeat"},
    },
}

GD_Relation = {
    ["name"] = "GD_Relation",
    ["id"] = 0,
    ["attribs"] = {
        {"relationId", "string"},
        {"role1", "uint32"},
        {"role2", "uint32"},
        {"buildTime", "uint32"},
        {"friendShip", "uint32"},
    },
}

GD_ApplyInfo = {
    ["name"] = "GD_ApplyInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"roleId", "uint32"},
        {"applyTime", "uint32"},
    },
}

GD_GiftInfo = {
    ["name"] = "GD_GiftInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"roleId", "uint32"},
        {"itemId", "uint32"},
        {"giftTime", "uint32"},
        {"isSend", "bool"},
    },
}

GD_FriendInfo = {
    ["name"] = "GD_FriendInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"mountFriendId", "uint32"},
        {"applyList", "GD_ApplyInfo", "repeat"},
        {"giftList", "GD_GiftInfo", "repeat"},
    },
}

GD_WineryInfo = {
    ["name"] = "GD_WineryInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"wineId", "uint32"},
        {"sellTime", "uint32"},
        {"drinkCount", "uint32"},
        {"visitList", "uint32", "repeat"},
        {"wineVisitList", "uint32", "repeat"},
    },
}

GD_FamilyTechInfo = {
    ["name"] = "GD_FamilyTechInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"techId", "uint32"},
        {"techLevel", "uint32"},
        {"activeTime", "uint32"},
    },
}

GD_AcademyInfo = {
    ["name"] = "GD_AcademyInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"academyLevel", "uint32"},
        {"techList", "GD_FamilyTechInfo", "repeat"},
    },
}

GD_FamilyMemberInfo = {
    ["name"] = "GD_FamilyMemberInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"roleId", "uint32"},
        {"position", "uint16"},
        {"weekScore", "uint32"},
        {"totalScore", "uint32"},
        {"donateCount", "uint32"},
    },
}

GD_FamilyApplicantInfo = {
    ["name"] = "GD_FamilyApplicantInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"roleId", "uint32"},
        {"applyTime", "uint32"},
    },
}

GD_RoleFamilyInfo = {
    ["name"] = "GD_RoleFamilyInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"familyId", "uint32"},
        {"last_quit", "uint32"},
    },
}

GD_FamilyInfo = {
    ["name"] = "GD_FamilyInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"familyId", "uint32"},
        {"level", "uint32"},
        {"rank", "uint32"},
        {"score", "uint32"},
        {"cash", "uint32"},
        {"buildTime", "uint32"},
        {"lastUpdata", "uint32"},
        {"familyName", "string"},
        {"purpose", "string"},
        {"academy", "GD_AcademyInfo"},
        {"members", "GD_FamilyMemberInfo", "repeat"},
        {"applyList", "GD_FamilyApplicantInfo", "repeat"},
    },
}

GD_ChatData = {
    ["name"] = "GD_ChatData",
    ["id"] = 0,
    ["attribs"] = {
        {"upCount", "uint32"},
        {"downCount", "uint32"},
        {"shutupTime", "uint32"},
        {"roleIds", "uint32", "repeat"},
    },
}

GD_BookInfo = {
    ["name"] = "GD_BookInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"bookId", "uint32"},
        {"pageList", "uint32", "repeat"},
    },
}

GD_OnlineInfo = {
    ["name"] = "GD_OnlineInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"lastTotalDuration", "uint32"},
        {"gainList", "uint32", "repeat"},
    },
}

GD_LevelGiftInfo = {
    ["name"] = "GD_LevelGiftInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"gainList", "uint32", "repeat"},
    },
}

GD_MonthSignInfo = {
    ["name"] = "GD_MonthSignInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"daySign", "uint16"},
        {"signCount", "uint32"},
        {"resignCount", "uint32"},
    },
}

GD_FirstPayInfo = {
    ["name"] = "GD_FirstPayInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"state", "uint16"},
    },
}

DG_AmassPayInfo = {
    ["name"] = "DG_AmassPayInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"totlePay", "uint32"},
        {"awardIds", "uint32", "repeat"},
    },
}

GD_ActivityInfo = {
    ["name"] = "GD_ActivityInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"onlineInfo", "GD_OnlineInfo"},
        {"levelGift", "GD_LevelGiftInfo"},
        {"monthSign", "GD_MonthSignInfo"},
        {"firstPayInfo", "GD_FirstPayInfo"},
        {"amasspayInfo", "DG_AmassPayInfo"},
    },
}

GD_AchieveInfo = {
    ["name"] = "GD_AchieveInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"achieveId", "uint32"},
        {"context", "string"},
    },
}

GD_RoleAchieve = {
    ["name"] = "GD_RoleAchieve",
    ["id"] = 0,
    ["attribs"] = {
        {"filed", "uint32"},
        {"finished", "uint32", "repeat"},
        {"running", "GD_AchieveInfo", "repeat"},
    },
}

