-- Date: 2015-10
-- File: msg_gc_notice.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define


FinancesNoticeRespBody = {
    ["name"] = "FinancesNoticeRespBody",
    ["id"] = 29501,
    ["attribs"] = {
        {"finances", "FinanceUnit", "repeat"},
    },
}

DisPlayNoticeRespBody = {
    ["name"] = "DisPlayNoticeRespBody",
    ["id"] = 29503,
    ["attribs"] = {
        {"mtp", "uint16"},
        {"args", "string", "repeat"},
    },
}

PackageNoticeRespBody = {
    ["name"] = "PackageNoticeRespBody",
    ["id"] = 29505,
    ["attribs"] = {
        {"itemList", "ItemInfo", "repeat"},
    },
}

TaskNoticeRespBody = {
    ["name"] = "TaskNoticeRespBody",
    ["id"] = 29507,
    ["attribs"] = {
        {"tasks", "TaskInfo", "repeat"},
    },
}

BuffNoticeRespBody = {
    ["name"] = "BuffNoticeRespBody",
    ["id"] = 29509,
    ["attribs"] = {
        {"buffs", "BuffInfo", "repeat"},
    },
}

FriendNoticeRespBody = {
    ["name"] = "FriendNoticeRespBody",
    ["id"] = 29511,
    ["attribs"] = {
        {"friendListFlag", "bool"},
        {"applyListFlag", "bool"},
        {"giftListFlag", "bool"},
    },
}

MailNoticeRespBody = {
    ["name"] = "MailNoticeRespBody",
    ["id"] = 29513,
    ["attribs"] = {
        {"mail", "MailDemo"},
    },
}

LevelUpNoticeRespBody = {
    ["name"] = "LevelUpNoticeRespBody",
    ["id"] = 29515,
    ["attribs"] = {
        {"oldLevel", "uint32"},
        {"curLevel", "uint32"},
        {"curExp", "uint32"},
        {"fpRank", "uint32"},
        {"oldfpRank", "uint32"},
    },
}

AttributeNoticeRespBody = {
    ["name"] = "AttributeNoticeRespBody",
    ["id"] = 29517,
    ["attribs"] = {
        {"attrs", "RoleAttrInfo"},
    },
}

ChatNoticeRespBody = {
    ["name"] = "ChatNoticeRespBody",
    ["id"] = 29519,
    ["attribs"] = {
        {"chatlist", "ChatUnit", "repeat"},
        {"teamlist", "TeamUnit", "repeat"},
    },
}

FamilyOwnNoticeRespBody = {
    ["name"] = "FamilyOwnNoticeRespBody",
    ["id"] = 29521,
    ["attribs"] = {
        {"isOwn", "bool"},
    },
}

RechargeNoticeRespBody = {
    ["name"] = "RechargeNoticeRespBody",
    ["id"] = 29523,
    ["attribs"] = {
        {"vipInfo", "VipInfo"},
        {"addDiamond", "uint32"},
    },
}

ApplyFamilyNoticeRespBody = {
    ["name"] = "ApplyFamilyNoticeRespBody",
    ["id"] = 29525,
}

ReloginNoticeRespBody = {
    ["name"] = "ReloginNoticeRespBody",
    ["id"] = 29527,
}

StopServiceNoticeRespBody = {
    ["name"] = "StopServiceNoticeRespBody",
    ["id"] = 29529,
}

PetNoticeRespBody = {
    ["name"] = "PetNoticeRespBody",
    ["id"] = 29531,
    ["attribs"] = {
        {"handleType", "uint16"},
    },
}

FamilyChangePositionRespBody = {
    ["name"] = "FamilyChangePositionRespBody",
    ["id"] = 29533,
    ["attribs"] = {
        {"positon", "uint16"},
    },
}

