-- Date: 2015-9
-- File: msg_ce.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与入口服务间的协议
--// 协议号分配：10000 ~ 19999


TagInfo = {
    ["name"] = "TagInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"isNew", "bool"},
        {"tagName", "string"},
    },
}

NoticeInfo = {
    ["name"] = "NoticeInfo",
    ["id"] = 0,
    ["attribs"] = {
        {"title", "string"},
        {"content", "string"},
    },
}

QuickLoginReqBody = {
    ["name"] = "QuickLoginReqBody",
    ["id"] = 10000,
    ["attribs"] = {
        {"verify_key", "string"},
        {"deviceToken", "string"},
        {"theDeviceInfo", "DeviceInfo"},
        {"theAppInfo", "AppVersionInfo"},
    },
}

QuickLoginRespBody = {
    ["name"] = "QuickLoginRespBody",
    ["id"] = 10001,
    ["attribs"] = {
        {"serialCode", "string"},
        {"userId", "uint32"},
        {"extData", "string"},
        {"serverList", "ServerInfo", "repeat"},
        {"zoneFlags", "uint32", "repeat"},
    },
}

QueryServerListReqBody = {
    ["name"] = "QueryServerListReqBody",
    ["id"] = 10002,
}

QueryServerListRespBody = {
    ["name"] = "QueryServerListRespBody",
    ["id"] = 10003,
    ["attribs"] = {
        {"serverList", "ServerInfo", "repeat"},
    },
}

ZTLoginReqBody = {
    ["name"] = "ZTLoginReqBody",
    ["id"] = 10004,
    ["attribs"] = {
        {"openId", "string"},
        {"token", "string"},
        {"verify_key", "string"},
        {"deviceToken", "string"},
        {"theDeviceInfo", "DeviceInfo"},
        {"theAppInfo", "AppVersionInfo"},
    },
}

ZTLoginRespBody = {
    ["name"] = "ZTLoginRespBody",
    ["id"] = 10005,
    ["attribs"] = {
        {"serialCode", "string"},
        {"userId", "uint32"},
        {"extData", "string"},
        {"serverList", "ServerInfo", "repeat"},
        {"zoneFlags", "uint32", "repeat"},
    },
}

GetNoticeTagListReqBody = {
    ["name"] = "GetNoticeTagListReqBody",
    ["id"] = 10006,
}

GetNoticeTagListRespBody = {
    ["name"] = "GetNoticeTagListRespBody",
    ["id"] = 10007,
    ["attribs"] = {
        {"tagList", "TagInfo", "repeat"},
        {"tagIndex", "uint32"},
        {"noticeInfo", "NoticeInfo"},
    },
}

GetNoticeReqBody = {
    ["name"] = "GetNoticeReqBody",
    ["id"] = 10008,
    ["attribs"] = {
        {"tagIndex", "uint32"},
    },
}

GetNoticeRespBody = {
    ["name"] = "GetNoticeRespBody",
    ["id"] = 10009,
    ["attribs"] = {
        {"noticeInfo", "NoticeInfo"},
    },
}

SelectZoneReqBody = {
    ["name"] = "SelectZoneReqBody",
    ["id"] = 10010,
    ["attribs"] = {
        {"zoneId", "uint32"},
    },
}

SelectZoneRespBody = {
    ["name"] = "SelectZoneRespBody",
    ["id"] = 10011,
    ["attribs"] = {
        {"currRank", "uint32"},
        {"totalCount", "uint32"},
    },
}

QueryRankReqBody = {
    ["name"] = "QueryRankReqBody",
    ["id"] = 10012,
    ["attribs"] = {
        {"zoneId", "uint32"},
    },
}

QueryRankRespBody = {
    ["name"] = "QueryRankRespBody",
    ["id"] = 10013,
    ["attribs"] = {
        {"currRank", "uint32"},
        {"totalCount", "uint32"},
    },
}

CancelRankReqBody = {
    ["name"] = "CancelRankReqBody",
    ["id"] = 10014,
}

CancelRankRespBody = {
    ["name"] = "CancelRankRespBody",
    ["id"] = 10015,
}

