-- Date: 2015-9
-- File: msg_cg_activity.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义用户活动相关协议
--// 协议号分配：22500 ~ 22999


QueryActivityListReqBody = {
    ["name"] = "QueryActivityListReqBody",
    ["id"] = 22500,
}

QueryActivityListRespBody = {
    ["name"] = "QueryActivityListRespBody",
    ["id"] = 22501,
    ["attribs"] = {
        {"actList", "ActivityInfo", "repeat"},
    },
}

QueryAmassPayReqBody = {
    ["name"] = "QueryAmassPayReqBody",
    ["id"] = 22502,
}

QueryAmassPayRespBody = {
    ["name"] = "QueryAmassPayRespBody",
    ["id"] = 22503,
    ["attribs"] = {
        {"amassPay", "uint32"},
        {"gainAwards", "uint32", "repeat"},
    },
}

GainAmassAwardReqBody = {
    ["name"] = "GainAmassAwardReqBody",
    ["id"] = 22504,
    ["attribs"] = {
        {"awardId", "uint32"},
    },
}

GainAmassAwardRespBody = {
    ["name"] = "GainAmassAwardRespBody",
    ["id"] = 22505,
}

QueryOnlineAwardReqBody = {
    ["name"] = "QueryOnlineAwardReqBody",
    ["id"] = 22506,
}

QueryOnlineAwardRespBody = {
    ["name"] = "QueryOnlineAwardRespBody",
    ["id"] = 22507,
    ["attribs"] = {
        {"getAwardList", "uint32", "repeat"},
        {"onlineTime", "uint32"},
    },
}

GainOnlineAwardReqBody = {
    ["name"] = "GainOnlineAwardReqBody",
    ["id"] = 22508,
    ["attribs"] = {
        {"index", "uint32"},
    },
}

GainOnlineAwardRespBody = {
    ["name"] = "GainOnlineAwardRespBody",
    ["id"] = 22509,
}

