-- Date: 2015-7
-- File: msg_cg_buff.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义用户buff相关协议
--// 协议号分配：23100 ~ 23199


GetBuffReqBody = {
    ["name"] = "GetBuffReqBody",
    ["id"] = 23100,
}

GetBuffRespBody = {
    ["name"] = "GetBuffRespBody",
    ["id"] = 23101,
    ["attribs"] = {
        {"buffs", "BuffInfo", "repeat"},
    },
}

