-- Date: 2015-7
-- File: msg_cg_task.lua
-- Auth: generated by auto tool 'lazybone'
-- Desc: message define
--// 定义了客户端与游戏服务间的部分协议
--// 定义用户任务相关协议
--// 协议号分配：21700 ~ 21799


QueryTasksReqBody = {
    ["name"] = "QueryTasksReqBody",
    ["id"] = 21700,
}

QueryTasksRespBody = {
    ["name"] = "QueryTasksRespBody",
    ["id"] = 21701,
    ["attribs"] = {
        {"vitalityInfo", "VitalityInfo"},
        {"tasks", "TaskInfo", "repeat"},
    },
}

GainTaskAwardReqBody = {
    ["name"] = "GainTaskAwardReqBody",
    ["id"] = 21702,
    ["attribs"] = {
        {"taskId", "uint32"},
    },
}

GainTaskAwardRespBody = {
    ["name"] = "GainTaskAwardRespBody",
    ["id"] = 21703,
    ["attribs"] = {
        {"addexp", "uint32"},
        {"vitality", "uint32"},
        {"award", "AwardInfo"},
        {"tasks", "TaskInfo", "repeat"},
    },
}

GainVitalityAwardReqBody = {
    ["name"] = "GainVitalityAwardReqBody",
    ["id"] = 21704,
    ["attribs"] = {
        {"index", "uint32"},
    },
}

GainVitalityAwardRespBody = {
    ["name"] = "GainVitalityAwardRespBody",
    ["id"] = 21705,
    ["attribs"] = {
        {"award", "AwardInfo"},
        {"vitalityInfo", "VitalityInfo"},
    },
}

