--[[TableTempleteItems.lua
--]]

TableTempleteItems= 
{
	{ TempleteID = 1.0, Name = '民阶装备碎片', Icon = 'goods_icon/eqiuppatch01', Instruction = '可以用于锻造10级装备', },
	{ TempleteID = 2.0, Name = '兵阶装备碎片', Icon = 'goods_icon/eqiuppatch02', Instruction = '可以用于锻造20级装备', },
	{ TempleteID = 3.0, Name = '仕阶装备碎片', Icon = 'goods_icon/eqiuppatch03', Instruction = '可以用于锻造30级装备', },
	{ TempleteID = 4.0, Name = '骑阶装备碎片', Icon = 'goods_icon/eqiuppatch04', Instruction = '可以用于锻造40级装备', },
	{ TempleteID = 5.0, Name = '将阶装备碎片', Icon = 'goods_icon/eqiuppatch05', Instruction = '可以用于锻造50级装备', },
	{ TempleteID = 6.0, Name = '王阶装备碎片', Icon = 'goods_icon/eqiuppatch06', Instruction = '可以用于锻造60级装备', },
	{ TempleteID = 7.0, Name = '帝阶装备碎片', Icon = 'goods_icon/eqiuppatch07', Instruction = '可以用于锻造70级装备', },
	{ TempleteID = 8.0, Name = '仙阶装备碎片', Icon = 'goods_icon/eqiuppatch08', Instruction = '可以用于锻造80级装备', },
	{ TempleteID = 9.0, Name = '无功能', Icon = 'goods_icon/icon_001', Instruction = '此物品无功能，请速速卖掉。', },
	{ TempleteID = 10.0, Name = '某东西', Icon = 'goods_icon/icon_001', Instruction = '某东西1004001', },
	{ TempleteID = 11.0, Name = '某东西', Icon = 'goods_icon/icon_001', Instruction = '某东西1004002', },
	{ TempleteID = 12.0, Name = '某东西', Icon = 'goods_icon/icon_001', Instruction = '某东西1004003', },
	{ TempleteID = 13.0, Name = '剑精', Icon = 'goods_icon/BladeSoulIcon1', Instruction = '某东西1005001', },
	{ TempleteID = 14.0, Name = '剑胆', Icon = 'goods_icon/BladeSoulIcon2', Instruction = '某东西1005002', },
	{ TempleteID = 15.0, Name = '剑魄', Icon = 'goods_icon/BladeSoulIcon3', Instruction = '某东西1005003', },
	{ TempleteID = 16.0, Name = '藏宝图', Icon = 'goods_icon/TreasureMap', Instruction = '藏宝图', },
	{ TempleteID = 17.0, Name = '小经验丹', Icon = 'goods_icon/ExpDan1', Instruction = '小经验丹，提升5%经验获得，持续1小时', },
	{ TempleteID = 18.0, Name = '中经验丹', Icon = 'goods_icon/ExpDan2', Instruction = '中经验丹，提升10%经验获得，持续1小时', },
	{ TempleteID = 19.0, Name = '大经验丹', Icon = 'goods_icon/ExpDan3', Instruction = '大经验丹，提升20%经验获得，持续1小时', },
	{ TempleteID = 20.0, Name = '某东西', Icon = 'goods_icon/icon_001', Instruction = '某东西1007002', },
	{ TempleteID = 21.0, Name = '某东西', Icon = 'goods_icon/icon_001', Instruction = '某东西1007003', },
	{ TempleteID = 22.0, Name = '星陨', Icon = 'goods_icon/MaterialIcon1', Instruction = '低级强化材料', },
	{ TempleteID = 23.0, Name = '烈锭', Icon = 'goods_icon/MaterialIcon2', Instruction = '中级强化材料', },
	{ TempleteID = 24.0, Name = '辉金', Icon = 'goods_icon/MaterialIcon3', Instruction = '高级强化材料', },
	{ TempleteID = 25.0, Name = '破境星', Icon = 'goods_icon/DanIcon', Instruction = '境界升阶丹1009001', },
	{ TempleteID = 26.0, Name = '红孩儿碎片', Icon = 'petpis_icon/PetPisIcon1', Instruction = '红孩儿碎片', },
	{ TempleteID = 27.0, Name = '小八碎片', Icon = 'petpis_icon/PetPisIcon2', Instruction = '小八碎片', },
	{ TempleteID = 28.0, Name = '灵明碎片', Icon = 'petpis_icon/PetPisIcon3', Instruction = '灵明碎片', },
	{ TempleteID = 29.0, Name = '六耳碎片', Icon = 'petpis_icon/PetPisIcon4', Instruction = '六耳碎片', },
	{ TempleteID = 30.0, Name = '通臂碎片', Icon = 'petpis_icon/PetPisIcon5', Instruction = '通臂碎片', },
	{ TempleteID = 31.0, Name = '卷帘碎片', Icon = 'petpis_icon/PetPisIcon6', Instruction = '卷帘碎片', },
	{ TempleteID = 32.0, Name = '小白龙碎片', Icon = 'petpis_icon/PetPisIcon7', Instruction = '小白龙碎片', },
	{ TempleteID = 33.0, Name = '兔兔碎片', Icon = 'petpis_icon/PetPisIcon8', Instruction = '兔兔碎片', },
	{ TempleteID = 34.0, Name = '萌骨碎片', Icon = 'petpis_icon/PetPisIcon9', Instruction = '萌骨碎片', },
	{ TempleteID = 35.0, Name = '银角碎片', Icon = 'petpis_icon/PetPisIcon10', Instruction = '银角碎片', },
	{ TempleteID = 36.0, Name = '慧元', Icon = 'goods_icon/PetFood1', Instruction = '宠物食材1', },
	{ TempleteID = 37.0, Name = '蟠桃', Icon = 'goods_icon/PetFood2', Instruction = '宠物食材2', },
	{ TempleteID = 38.0, Name = '人参果', Icon = 'goods_icon/PetFood3', Instruction = '宠物食材3', },
	{ TempleteID = 39.0, Name = '免死符', Icon = 'goods_icon/DeathIcon', Instruction = '免死符，即使偶遇午夜惊魂，只要使用它，阎王爸爸也不会抓走你滴。', },
	{ TempleteID = 40.0, Name = '战灵精元・星', Icon = 'goods_icon/PetAdv1', Instruction = '宠物升阶材料1', },
	{ TempleteID = 41.0, Name = '战灵精元・烈', Icon = 'goods_icon/PetAdv2', Instruction = '宠物升阶材料2', },
	{ TempleteID = 42.0, Name = '战灵精元・辉', Icon = 'goods_icon/PetAdv3', Instruction = '宠物升阶材料3', },
	{ TempleteID = 43.0, Name = '传音喇叭', Icon = 'goods_icon/horn', Instruction = '传音喇叭，使用一只即可让全服玩家收到你的简讯。', },
	{ TempleteID = 44.0, Name = '某东西', Icon = 'goods_icon/icon_001', Instruction = '某东西1015002', },
	{ TempleteID = 45.0, Name = '某东西', Icon = 'goods_icon/icon_001', Instruction = '某东西1015003', },
	{ TempleteID = 46.0, Name = '某东西1016001', Icon = 'goods_icon/icon_001', Instruction = '某东西1016001', },
	{ TempleteID = 47.0, Name = '某东西1016002', Icon = 'goods_icon/icon_001', Instruction = '某东西1016002', },
	{ TempleteID = 48.0, Name = '某东西1016003', Icon = 'goods_icon/icon_001', Instruction = '某东西1016003', },
	{ TempleteID = 49.0, Name = '碎裂生命宝石', Icon = 'goods_icon/stone0101', },
	{ TempleteID = 50.0, Name = '无瑕生命宝石', Icon = 'goods_icon/stone0102', },
	{ TempleteID = 51.0, Name = '璀璨生命宝石', Icon = 'goods_icon/stone0103', },
	{ TempleteID = 52.0, Name = '星芒生命宝石', Icon = 'goods_icon/stone0104', },
	{ TempleteID = 53.0, Name = '尊爵生命宝石', Icon = 'goods_icon/stone0105', },
	{ TempleteID = 54.0, Name = '碎裂攻击宝石', Icon = 'goods_icon/stone0201', },
	{ TempleteID = 55.0, Name = '无瑕攻击宝石', Icon = 'goods_icon/stone0202', },
	{ TempleteID = 56.0, Name = '璀璨攻击宝石', Icon = 'goods_icon/stone0203', },
	{ TempleteID = 57.0, Name = '星芒攻击宝石', Icon = 'goods_icon/stone0204', },
	{ TempleteID = 58.0, Name = '尊爵攻击宝石', Icon = 'goods_icon/stone0205', },
	{ TempleteID = 59.0, Name = '碎裂防御宝石', Icon = 'goods_icon/stone0301', },
	{ TempleteID = 60.0, Name = '无瑕防御宝石', Icon = 'goods_icon/stone0302', },
	{ TempleteID = 61.0, Name = '璀璨防御宝石', Icon = 'goods_icon/stone0303', },
	{ TempleteID = 62.0, Name = '星芒防御宝石', Icon = 'goods_icon/stone0304', },
	{ TempleteID = 63.0, Name = '尊爵防御宝石', Icon = 'goods_icon/stone0305', },
	{ TempleteID = 64.0, Name = '碎裂暴率宝石', Icon = 'goods_icon/stone0401', },
	{ TempleteID = 65.0, Name = '无瑕暴率宝石', Icon = 'goods_icon/stone0402', },
	{ TempleteID = 66.0, Name = '璀璨暴率宝石', Icon = 'goods_icon/stone0403', },
	{ TempleteID = 67.0, Name = '星芒暴率宝石', Icon = 'goods_icon/stone0404', },
	{ TempleteID = 68.0, Name = '尊爵暴率宝石', Icon = 'goods_icon/stone0405', },
	{ TempleteID = 69.0, Name = '碎裂暴伤宝石', Icon = 'goods_icon/stone0501', },
	{ TempleteID = 70.0, Name = '无瑕暴伤宝石', Icon = 'goods_icon/stone0502', },
	{ TempleteID = 71.0, Name = '璀璨暴伤宝石', Icon = 'goods_icon/stone0503', },
	{ TempleteID = 72.0, Name = '星芒暴伤宝石', Icon = 'goods_icon/stone0504', },
	{ TempleteID = 73.0, Name = '尊爵暴伤宝石', Icon = 'goods_icon/stone0505', },
	{ TempleteID = 74.0, Name = '碎裂韧性宝石', Icon = 'goods_icon/stone0601', },
	{ TempleteID = 75.0, Name = '无瑕韧性宝石', Icon = 'goods_icon/stone0602', },
	{ TempleteID = 76.0, Name = '璀璨韧性宝石', Icon = 'goods_icon/stone0603', },
	{ TempleteID = 77.0, Name = '星芒韧性宝石', Icon = 'goods_icon/stone0604', },
	{ TempleteID = 78.0, Name = '尊爵韧性宝石', Icon = 'goods_icon/stone0605', },
	{ TempleteID = 79.0, Name = '碎裂抗性宝石', Icon = 'goods_icon/stone0701', },
	{ TempleteID = 80.0, Name = '无瑕抗性宝石', Icon = 'goods_icon/stone0702', },
	{ TempleteID = 81.0, Name = '璀璨抗性宝石', Icon = 'goods_icon/stone0703', },
	{ TempleteID = 82.0, Name = '星芒抗性宝石', Icon = 'goods_icon/stone0704', },
	{ TempleteID = 83.0, Name = '尊爵抗性宝石', Icon = 'goods_icon/stone0705', },
	{ TempleteID = 84.0, Name = '碎裂格挡宝石', Icon = 'goods_icon/stone0801', },
	{ TempleteID = 85.0, Name = '无瑕格挡宝石', Icon = 'goods_icon/stone0802', },
	{ TempleteID = 86.0, Name = '璀璨格挡宝石', Icon = 'goods_icon/stone0803', },
	{ TempleteID = 87.0, Name = '星芒格挡宝石', Icon = 'goods_icon/stone0804', },
	{ TempleteID = 88.0, Name = '尊爵格挡宝石', Icon = 'goods_icon/stone0805', },
	{ TempleteID = 89.0, Name = '碎裂穿透宝石', Icon = 'goods_icon/stone0901', },
	{ TempleteID = 90.0, Name = '无瑕穿透宝石', Icon = 'goods_icon/stone0902', },
	{ TempleteID = 91.0, Name = '璀璨穿透宝石', Icon = 'goods_icon/stone0903', },
	{ TempleteID = 92.0, Name = '星芒穿透宝石', Icon = 'goods_icon/stone0904', },
	{ TempleteID = 93.0, Name = '尊爵穿透宝石', Icon = 'goods_icon/stone0905', },
	{ TempleteID = 94.0, Name = '碎裂闪避宝石', Icon = 'goods_icon/stone1001', },
	{ TempleteID = 95.0, Name = '无瑕闪避宝石', Icon = 'goods_icon/stone1002', },
	{ TempleteID = 96.0, Name = '璀璨闪避宝石', Icon = 'goods_icon/stone1003', },
	{ TempleteID = 97.0, Name = '星芒闪避宝石', Icon = 'goods_icon/stone1004', },
	{ TempleteID = 98.0, Name = '尊爵闪避宝石', Icon = 'goods_icon/stone1005', },
	{ TempleteID = 99.0, Name = '碎裂属强宝石', Icon = 'goods_icon/stone1101', },
	{ TempleteID = 100.0, Name = '无瑕属强宝石', Icon = 'goods_icon/stone1102', },
	{ TempleteID = 101.0, Name = '璀璨属强宝石', Icon = 'goods_icon/stone1103', },
	{ TempleteID = 102.0, Name = '星芒属强宝石', Icon = 'goods_icon/stone1104', },
	{ TempleteID = 103.0, Name = '尊爵属强宝石', Icon = 'goods_icon/stone1105', },
	{ TempleteID = 104.0, Name = '碎裂火攻宝石', Icon = 'goods_icon/stone1201', },
	{ TempleteID = 105.0, Name = '无瑕火攻宝石', Icon = 'goods_icon/stone1202', },
	{ TempleteID = 106.0, Name = '璀璨火攻宝石', Icon = 'goods_icon/stone1203', },
	{ TempleteID = 107.0, Name = '星芒火攻宝石', Icon = 'goods_icon/stone1204', },
	{ TempleteID = 108.0, Name = '尊爵火攻宝石', Icon = 'goods_icon/stone1205', },
	{ TempleteID = 109.0, Name = '碎裂冰攻宝石', Icon = 'goods_icon/stone1301', },
	{ TempleteID = 110.0, Name = '无瑕冰攻宝石', Icon = 'goods_icon/stone1302', },
	{ TempleteID = 111.0, Name = '璀璨冰攻宝石', Icon = 'goods_icon/stone1303', },
	{ TempleteID = 112.0, Name = '星芒冰攻宝石', Icon = 'goods_icon/stone1304', },
	{ TempleteID = 113.0, Name = '尊爵冰攻宝石', Icon = 'goods_icon/stone1305', },
	{ TempleteID = 114.0, Name = '碎裂雷攻宝石', Icon = 'goods_icon/stone1401', },
	{ TempleteID = 115.0, Name = '无瑕雷攻宝石', Icon = 'goods_icon/stone1402', },
	{ TempleteID = 116.0, Name = '璀璨雷攻宝石', Icon = 'goods_icon/stone1403', },
	{ TempleteID = 117.0, Name = '星芒雷攻宝石', Icon = 'goods_icon/stone1404', },
	{ TempleteID = 118.0, Name = '尊爵雷攻宝石', Icon = 'goods_icon/stone1405', },
	{ TempleteID = 119.0, Name = '碎裂再生宝石', Icon = 'goods_icon/stone1501', },
	{ TempleteID = 120.0, Name = '无瑕再生宝石', Icon = 'goods_icon/stone1502', },
	{ TempleteID = 121.0, Name = '璀璨再生宝石', Icon = 'goods_icon/stone1503', },
	{ TempleteID = 122.0, Name = '星芒再生宝石', Icon = 'goods_icon/stone1504', },
	{ TempleteID = 123.0, Name = '尊爵再生宝石', Icon = 'goods_icon/stone1505', },
	{ TempleteID = 124.0, Name = '碎裂吸血宝石', Icon = 'goods_icon/stone1601', },
	{ TempleteID = 125.0, Name = '无瑕吸血宝石', Icon = 'goods_icon/stone1602', },
	{ TempleteID = 126.0, Name = '璀璨吸血宝石', Icon = 'goods_icon/stone1603', },
	{ TempleteID = 127.0, Name = '星芒吸血宝石', Icon = 'goods_icon/stone1604', },
	{ TempleteID = 128.0, Name = '尊爵吸血宝石', Icon = 'goods_icon/stone1605', },
	{ TempleteID = 129.0, Name = '某美人卷轴', Icon = 'goods_icon/icon_001', Instruction = '某美人卷轴1018001', },
	{ TempleteID = 130.0, Name = '某美人卷轴', Icon = 'goods_icon/icon_001', Instruction = '某美人卷轴1018002', },
	{ TempleteID = 131.0, Name = '某美人卷轴', Icon = 'goods_icon/icon_001', Instruction = '某美人卷轴1018003', },
	{ TempleteID = 132.0, Name = '某宝箱', Icon = 'goods_icon/12', Instruction = '某宝箱1019001', },
	{ TempleteID = 133.0, Name = '某宝箱', Icon = 'goods_icon/12', Instruction = '某宝箱1019001', },
	{ TempleteID = 134.0, Name = '某宝箱', Icon = 'goods_icon/12', Instruction = '某宝箱1019001', },
	{ TempleteID = 135.0, Name = '某宝箱', Icon = 'goods_icon/12', Instruction = '某宝箱1019002', },
	{ TempleteID = 136.0, Name = '某宝箱', Icon = 'goods_icon/12', Instruction = '某宝箱1019002', },
	{ TempleteID = 137.0, Name = '某宝箱', Icon = 'goods_icon/12', Instruction = '某宝箱1019002', },
	{ TempleteID = 138.0, Name = '某宝箱', Icon = 'goods_icon/12', Instruction = '某宝箱1019003', },
	{ TempleteID = 139.0, Name = '某宝箱', Icon = 'goods_icon/12', Instruction = '某宝箱1019003', },
	{ TempleteID = 140.0, Name = '某宝箱', Icon = 'goods_icon/12', Instruction = '某宝箱1019003', },
	{ TempleteID = 141.0, Name = '初生生命丹', Icon = 'goods_icon/fairylanddan11', Instruction = '境界丹ID1{{1,1},{2,-2}}', },
	{ TempleteID = 142.0, Name = '锻体生命丹', Icon = 'goods_icon/fairylanddan11', Instruction = '境界丹ID2{{1,2}}', },
	{ TempleteID = 143.0, Name = '洗髓生命丹', Icon = 'goods_icon/fairylanddan11', Instruction = '境界丹ID3{{1,3}}', },
	{ TempleteID = 144.0, Name = '化神生命丹', Icon = 'goods_icon/fairylanddan11', Instruction = '境界丹ID4{{1,4}}', },
	{ TempleteID = 145.0, Name = '真元生命丹', Icon = 'goods_icon/fairylanddan11', Instruction = '境界丹ID5{{1,5}}', },
	{ TempleteID = 146.0, Name = '初生武神丹', Icon = 'goods_icon/fairylanddan06', Instruction = '境界丹ID6{{2,1}}', },
	{ TempleteID = 147.0, Name = '锻体武神丹', Icon = 'goods_icon/fairylanddan06', Instruction = '境界丹ID7{{2,2}}', },
	{ TempleteID = 148.0, Name = '洗髓武神丹', Icon = 'goods_icon/fairylanddan06', Instruction = '境界丹ID8{{2,3}}', },
	{ TempleteID = 149.0, Name = '化神武神丹', Icon = 'goods_icon/fairylanddan06', Instruction = '境界丹ID9{{2,4}}', },
	{ TempleteID = 150.0, Name = '真元武神丹', Icon = 'goods_icon/fairylanddan06', Instruction = '境界丹ID10{{2,5}}', },
	{ TempleteID = 151.0, Name = '初生钢体丹', Icon = 'goods_icon/fairylanddan04', Instruction = '境界丹ID11{{3,1}}', },
	{ TempleteID = 152.0, Name = '锻体钢体丹', Icon = 'goods_icon/fairylanddan04', Instruction = '境界丹ID12{{3,2}}', },
	{ TempleteID = 153.0, Name = '洗髓钢体丹', Icon = 'goods_icon/fairylanddan04', Instruction = '境界丹ID13{{3,3}}', },
	{ TempleteID = 154.0, Name = '化神钢体丹', Icon = 'goods_icon/fairylanddan04', Instruction = '境界丹ID14{{3,4}}', },
	{ TempleteID = 155.0, Name = '真元钢体丹', Icon = 'goods_icon/fairylanddan04', Instruction = '境界丹ID15{{3,5}}', },
	{ TempleteID = 156.0, Name = '初生杀生丹', Icon = 'goods_icon/fairylanddan01', Instruction = '境界丹ID16{{4,1}}', },
	{ TempleteID = 157.0, Name = '锻体杀生丹', Icon = 'goods_icon/fairylanddan01', Instruction = '境界丹ID17{{4,2}}', },
	{ TempleteID = 158.0, Name = '洗髓杀生丹', Icon = 'goods_icon/fairylanddan01', Instruction = '境界丹ID18{{4,3}}', },
	{ TempleteID = 159.0, Name = '化神杀生丹', Icon = 'goods_icon/fairylanddan01', Instruction = '境界丹ID19{{4,4}}', },
	{ TempleteID = 160.0, Name = '真元杀生丹', Icon = 'goods_icon/fairylanddan01', Instruction = '境界丹ID20{{4,5}}', },
	{ TempleteID = 161.0, Name = '初生夺命丹', Icon = 'goods_icon/fairylanddan02', Instruction = '境界丹ID21{{5,1}}', },
	{ TempleteID = 162.0, Name = '锻体夺命丹', Icon = 'goods_icon/fairylanddan02', Instruction = '境界丹ID22{{5,2}}', },
	{ TempleteID = 163.0, Name = '洗髓夺命丹', Icon = 'goods_icon/fairylanddan02', Instruction = '境界丹ID23{{5,3}}', },
	{ TempleteID = 164.0, Name = '化神夺命丹', Icon = 'goods_icon/fairylanddan02', Instruction = '境界丹ID24{{5,4}}', },
	{ TempleteID = 165.0, Name = '真元夺命丹', Icon = 'goods_icon/fairylanddan02', Instruction = '境界丹ID25{{5,5}}', },
	{ TempleteID = 166.0, Name = '初生坚韧丹', Icon = 'goods_icon/fairylanddan08', Instruction = '境界丹ID26{{6,1}}', },
	{ TempleteID = 167.0, Name = '锻体坚韧丹', Icon = 'goods_icon/fairylanddan08', Instruction = '境界丹ID27{{6,2}}', },
	{ TempleteID = 168.0, Name = '洗髓坚韧丹', Icon = 'goods_icon/fairylanddan08', Instruction = '境界丹ID28{{6,3}}', },
	{ TempleteID = 169.0, Name = '化神坚韧丹', Icon = 'goods_icon/fairylanddan08', Instruction = '境界丹ID29{{6,4}}', },
	{ TempleteID = 170.0, Name = '真元坚韧丹', Icon = 'goods_icon/fairylanddan08', Instruction = '境界丹ID30{{6,5}}', },
	{ TempleteID = 171.0, Name = '初生固元丹', Icon = 'goods_icon/fairylanddan07', Instruction = '境界丹ID31{{7,1}}', },
	{ TempleteID = 172.0, Name = '锻体固元丹', Icon = 'goods_icon/fairylanddan07', Instruction = '境界丹ID32{{7,2}}', },
	{ TempleteID = 173.0, Name = '洗髓固元丹', Icon = 'goods_icon/fairylanddan07', Instruction = '境界丹ID33{{7,3}}', },
	{ TempleteID = 174.0, Name = '化神固元丹', Icon = 'goods_icon/fairylanddan07', Instruction = '境界丹ID34{{7,4}}', },
	{ TempleteID = 175.0, Name = '真元固元丹', Icon = 'goods_icon/fairylanddan07', Instruction = '境界丹ID35{{7,5}}', },
	{ TempleteID = 176.0, Name = '初生守护丹', Icon = 'goods_icon/fairylanddan05', Instruction = '境界丹ID36{{8,1}}', },
	{ TempleteID = 177.0, Name = '锻体守护丹', Icon = 'goods_icon/fairylanddan05', Instruction = '境界丹ID37{{8,2}}', },
	{ TempleteID = 178.0, Name = '洗髓守护丹', Icon = 'goods_icon/fairylanddan05', Instruction = '境界丹ID38{{8,3}}', },
	{ TempleteID = 179.0, Name = '化神守护丹', Icon = 'goods_icon/fairylanddan05', Instruction = '境界丹ID39{{8,4}}', },
	{ TempleteID = 180.0, Name = '真元守护丹', Icon = 'goods_icon/fairylanddan05', Instruction = '境界丹ID40{{8,5}}', },
	{ TempleteID = 181.0, Name = '初生破界丹', Icon = 'goods_icon/fairylanddan03', Instruction = '境界丹ID41{{9,1}}', },
	{ TempleteID = 182.0, Name = '锻体破界丹', Icon = 'goods_icon/fairylanddan03', Instruction = '境界丹ID42{{9,2}}', },
	{ TempleteID = 183.0, Name = '洗髓破界丹', Icon = 'goods_icon/fairylanddan03', Instruction = '境界丹ID43{{9,3}}', },
	{ TempleteID = 184.0, Name = '化神破界丹', Icon = 'goods_icon/fairylanddan03', Instruction = '境界丹ID44{{9,4}}', },
	{ TempleteID = 185.0, Name = '真元破界丹', Icon = 'goods_icon/fairylanddan03', Instruction = '境界丹ID45{{9,5}}', },
	{ TempleteID = 186.0, Name = '初生无伤丹', Icon = 'goods_icon/fairylanddan09', Instruction = '境界丹ID46{{10,1}}', },
	{ TempleteID = 187.0, Name = '锻体无伤丹', Icon = 'goods_icon/fairylanddan09', Instruction = '境界丹ID47{{10,2}}', },
	{ TempleteID = 188.0, Name = '洗髓无伤丹', Icon = 'goods_icon/fairylanddan09', Instruction = '境界丹ID48{{10,3}}', },
	{ TempleteID = 189.0, Name = '化神无伤丹', Icon = 'goods_icon/fairylanddan09', Instruction = '境界丹ID49{{10,4}}', },
	{ TempleteID = 190.0, Name = '真元无伤丹', Icon = 'goods_icon/fairylanddan09', Instruction = '境界丹ID50{{10,5}}', },
	{ TempleteID = 191.0, Name = '初生元素丹', Icon = 'goods_icon/fairylanddan10', Instruction = '境界丹ID51{{11,1}}', },
	{ TempleteID = 192.0, Name = '锻体元素丹', Icon = 'goods_icon/fairylanddan10', Instruction = '境界丹ID52{{11,2}}', },
	{ TempleteID = 193.0, Name = '洗髓元素丹', Icon = 'goods_icon/fairylanddan10', Instruction = '境界丹ID53{{11,3}}', },
	{ TempleteID = 194.0, Name = '化神元素丹', Icon = 'goods_icon/fairylanddan10', Instruction = '境界丹ID54{{11,4}}', },
	{ TempleteID = 195.0, Name = '真元元素丹', Icon = 'goods_icon/fairylanddan10', Instruction = '境界丹ID55{{11,5}}', },
	{ TempleteID = 196.0, Name = '初生疗伤丹', Icon = 'goods_icon/fairylanddan12', Instruction = '境界丹ID56{{15,1}}', },
	{ TempleteID = 197.0, Name = '锻体疗伤丹', Icon = 'goods_icon/fairylanddan12', Instruction = '境界丹ID57{{15,2}}', },
	{ TempleteID = 198.0, Name = '洗髓疗伤丹', Icon = 'goods_icon/fairylanddan12', Instruction = '境界丹ID58{{15,3}}', },
	{ TempleteID = 199.0, Name = '化神疗伤丹', Icon = 'goods_icon/fairylanddan12', Instruction = '境界丹ID59{{15,4}}', },
	{ TempleteID = 200.0, Name = '真元疗伤丹', Icon = 'goods_icon/fairylanddan12', Instruction = '境界丹ID60{{15,5}}', },
	{ TempleteID = 201.0, Name = '剑魂・风', Icon = 'goods_icon/BladeSoul1', Instruction = '剑魂1', },
	{ TempleteID = 202.0, Name = '剑魂・雨', Icon = 'goods_icon/BladeSoul2', Instruction = '剑魂2', },
	{ TempleteID = 203.0, Name = '剑魂・雷', Icon = 'goods_icon/BladeSoul3', Instruction = '剑魂3', },
	{ TempleteID = 204.0, Name = '剑魂・电', Icon = 'goods_icon/BladeSoul4', Instruction = '剑魂4', },
	{ TempleteID = 205.0, Name = '剑魂・云', Icon = 'goods_icon/BladeSoul5', Instruction = '剑魂5', },
	{ TempleteID = 206.0, Name = '剑魂・雾', Icon = 'goods_icon/BladeSoul6', Instruction = '剑魂6', },
	{ TempleteID = 207.0, Name = '剑魂・雪', Icon = 'goods_icon/BladeSoul7', Instruction = '剑魂7', },
	{ TempleteID = 208.0, Name = '剑魂・霜', Icon = 'goods_icon/BladeSoul8', Instruction = '剑魂8', },
	{ TempleteID = 209.0, Name = '剑魂・昼', Icon = 'goods_icon/BladeSoul9', Instruction = '剑魂9', },
	{ TempleteID = 210.0, Name = '剑魂・夜', Icon = 'goods_icon/BladeSoul10', Instruction = '剑魂10', },
	{ TempleteID = 211.0, Name = '钴蓝头盔图谱', Icon = 'goods_icon/piceqiup1_2', Instruction = '可以用于锻造蓝色头部装备的图谱', },
	{ TempleteID = 212.0, Name = '钴蓝盔甲图谱', Icon = 'goods_icon/piceqiup2_2', Instruction = '可以用于锻造蓝色身部装备的图谱', },
	{ TempleteID = 213.0, Name = '钴蓝护臂图谱', Icon = 'goods_icon/piceqiup4_2', Instruction = '可以用于锻造蓝色手部装备的图谱', },
	{ TempleteID = 214.0, Name = '钴蓝战靴图谱', Icon = 'goods_icon/piceqiup3_2', Instruction = '可以用于锻造蓝色腿部装备的图谱', },
	{ TempleteID = 215.0, Name = '钴蓝兵刃图谱', Icon = 'goods_icon/piceqiup5_2', Instruction = '可以用于锻造蓝色武器部装备的图谱', },
	{ TempleteID = 216.0, Name = '钴蓝饰品图谱', Icon = 'goods_icon/piceqiup7_2', Instruction = '可以用于锻造蓝色项链部装备的图谱', },
	{ TempleteID = 217.0, Name = '钴蓝戒指图谱', Icon = 'goods_icon/piceqiup6_2', Instruction = '可以用于锻造蓝色戒指部装备的图谱', },
	{ TempleteID = 218.0, Name = '钴蓝羽翼图谱', Icon = 'goods_icon/icon_002', Instruction = '可以用于锻造蓝色翅膀部装备的图谱', },
	{ TempleteID = 219.0, Name = '钴蓝时装图谱', Icon = 'goods_icon/icon_002', Instruction = '可以用于锻造蓝色时装部装备的图谱', },
	{ TempleteID = 220.0, Name = '钴蓝光环图谱', Icon = 'goods_icon/icon_002', Instruction = '可以用于锻造蓝色光环部装备的图谱', },
	{ TempleteID = 221.0, Name = '紫晶头盔图谱', Icon = 'goods_icon/piceqiup1_3', Instruction = '可以用于锻造紫色头部装备的图谱', },
	{ TempleteID = 222.0, Name = '紫晶盔甲图谱', Icon = 'goods_icon/piceqiup2_3', Instruction = '可以用于锻造紫色身部装备的图谱', },
	{ TempleteID = 223.0, Name = '紫晶护臂图谱', Icon = 'goods_icon/piceqiup4_3', Instruction = '可以用于锻造紫色手部装备的图谱', },
	{ TempleteID = 224.0, Name = '紫晶战靴图谱', Icon = 'goods_icon/piceqiup3_3', Instruction = '可以用于锻造紫色腿部装备的图谱', },
	{ TempleteID = 225.0, Name = '紫晶兵刃图谱', Icon = 'goods_icon/piceqiup5_3', Instruction = '可以用于锻造紫色武器部装备的图谱', },
	{ TempleteID = 226.0, Name = '紫晶饰品图谱', Icon = 'goods_icon/piceqiup7_3', Instruction = '可以用于锻造紫色项链部装备的图谱', },
	{ TempleteID = 227.0, Name = '紫晶戒指图谱', Icon = 'goods_icon/piceqiup6_3', Instruction = '可以用于锻造紫色戒指部装备的图谱', },
	{ TempleteID = 228.0, Name = '紫晶羽翼图谱', Icon = 'goods_icon/icon_002', Instruction = '可以用于锻造紫色翅膀部装备的图谱', },
	{ TempleteID = 229.0, Name = '紫晶时装图谱', Icon = 'goods_icon/icon_002', Instruction = '可以用于锻造紫色时装部装备的图谱', },
	{ TempleteID = 230.0, Name = '紫晶光环图谱', Icon = 'goods_icon/icon_002', Instruction = '可以用于锻造紫色光环部装备的图谱', },
	{ TempleteID = 231.0, Name = '辉阳头盔图谱', Icon = 'goods_icon/piceqiup1_4', Instruction = '可以用于锻造橙色头部装备的图谱', },
	{ TempleteID = 232.0, Name = '辉阳盔甲图谱', Icon = 'goods_icon/piceqiup2_4', Instruction = '可以用于锻造橙色身部装备的图谱', },
	{ TempleteID = 233.0, Name = '辉阳护臂图谱', Icon = 'goods_icon/piceqiup4_4', Instruction = '可以用于锻造橙色手部装备的图谱', },
	{ TempleteID = 234.0, Name = '辉阳战靴图谱', Icon = 'goods_icon/piceqiup3_4', Instruction = '可以用于锻造橙色腿部装备的图谱', },
	{ TempleteID = 235.0, Name = '辉阳兵刃图谱', Icon = 'goods_icon/piceqiup5_4', Instruction = '可以用于锻造橙色武器部装备的图谱', },
	{ TempleteID = 236.0, Name = '辉阳饰品图谱', Icon = 'goods_icon/piceqiup7_4', Instruction = '可以用于锻造橙色项链部装备的图谱', },
	{ TempleteID = 237.0, Name = '辉阳戒指图谱', Icon = 'goods_icon/piceqiup6_4', Instruction = '可以用于锻造橙色戒指部装备的图谱', },
	{ TempleteID = 238.0, Name = '辉阳羽翼图谱', Icon = 'goods_icon/icon_002', Instruction = '可以用于锻造橙色翅膀部装备的图谱', },
	{ TempleteID = 239.0, Name = '辉阳时装图谱', Icon = 'goods_icon/icon_003', Instruction = '可以用于锻造橙色时装部装备的图谱', },
	{ TempleteID = 240.0, Name = '辉阳光环图谱', Icon = 'goods_icon/icon_004', Instruction = '可以用于锻造橙色光环部装备的图谱', },
	{ TempleteID = 241.0, Name = '宝箱1', Icon = 'goods_icon/12', Instruction = 'ID为400001的宝箱', },
	{ TempleteID = 242.0, Name = '宝箱2', Icon = 'goods_icon/12', Instruction = 'ID为400002的宝箱', },
	{ TempleteID = 243.0, Name = '宝箱3', Icon = 'goods_icon/12', Instruction = 'ID为400003的宝箱', },
	{ TempleteID = 244.0, Name = '宝箱4', Icon = 'goods_icon/12', Instruction = 'ID为400004的宝箱', },
	{ TempleteID = 245.0, Name = '宝箱5', Icon = 'goods_icon/12', Instruction = 'ID为400005的宝箱', },
	{ TempleteID = 246.0, Name = '宝箱6', Icon = 'goods_icon/12', Instruction = 'ID为400006的宝箱', },
	{ TempleteID = 247.0, Name = '宝箱7', Icon = 'goods_icon/12', Instruction = 'ID为400007的宝箱', },
	{ TempleteID = 248.0, Name = '宝箱8', Icon = 'goods_icon/12', Instruction = 'ID为400008的宝箱', },
	{ TempleteID = 249.0, Name = '宝箱9', Icon = 'goods_icon/12', Instruction = 'ID为400009的宝箱', },
	{ TempleteID = 250.0, Name = '宝箱10', Icon = 'goods_icon/12', Instruction = 'ID为400010的宝箱', },
	{ TempleteID = 251.0, Name = '宝箱11', Icon = 'goods_icon/12', Instruction = 'ID为400011的宝箱', },
	{ TempleteID = 252.0, Name = '宝箱12', Icon = 'goods_icon/12', Instruction = 'ID为400012的宝箱', },
	{ TempleteID = 253.0, Name = '玫瑰', Icon = 'goods_icon/FriendGifts01', Instruction = '一份赠与好友的小小心意，使用可以增加10亲密度。', },
	{ TempleteID = 254.0, Name = '花束', Icon = 'goods_icon/FriendGifts02', Instruction = '一份赠与好友的小小心意，使用可以增加50亲密度。', },
	{ TempleteID = 255.0, Name = '大花束', Icon = 'goods_icon/FriendGifts03', Instruction = '一份赠与好友的小小心意，使用可以增加200亲密度。', },
	{ TempleteID = 256.0, Name = '小幅女儿国国王画卷', Icon = 'goods_icon/Cards1', Instruction = '打开后有可能获得一张女儿国国王美人图', },
	{ TempleteID = 257.0, Name = '小幅玉兔画卷', Icon = 'goods_icon/Cards1', Instruction = '打开后有可能获得一张玉兔美人图', },
	{ TempleteID = 258.0, Name = '小幅杏仙画卷', Icon = 'goods_icon/Cards1', Instruction = '打开后有可能获得一张杏仙美人图', },
	{ TempleteID = 259.0, Name = '小幅铁扇公主画卷', Icon = 'goods_icon/Cards1', Instruction = '打开后有可能获得一张铁扇公主美人图', },
	{ TempleteID = 260.0, Name = '小幅盘丝大仙画卷', Icon = 'goods_icon/Cards1', Instruction = '打开后有可能获得一张盘丝大仙美人图', },
	{ TempleteID = 261.0, Name = '小幅地涌夫人画卷', Icon = 'goods_icon/Cards1', Instruction = '打开后有可能获得一张地涌夫人美人图', },
	{ TempleteID = 262.0, Name = '小幅白骨夫人画卷', Icon = 'goods_icon/Cards1', Instruction = '打开后有可能获得一张白骨夫人美人图', },
	{ TempleteID = 263.0, Name = '小幅琵琶蝎子精画卷', Icon = 'goods_icon/Cards1', Instruction = '打开后有可能获得一张琵琶蝎子精美人图', },
	{ TempleteID = 264.0, Name = '小幅胡喜媚画卷', Icon = 'goods_icon/Cards1', Instruction = '打开后有可能获得一张胡喜媚美人图', },
	{ TempleteID = 265.0, Name = '小幅妲己画卷', Icon = 'goods_icon/Cards1', Instruction = '打开后有可能获得一张妲己美人图', },
	{ TempleteID = 266.0, Name = '女儿国国王画卷', Icon = 'goods_icon/Cards2', Instruction = '打开后有几率获得若干张女儿国国王美人图', },
	{ TempleteID = 267.0, Name = '玉兔画卷', Icon = 'goods_icon/Cards2', Instruction = '打开后有几率获得若干张玉兔美人图', },
	{ TempleteID = 268.0, Name = '杏仙画卷', Icon = 'goods_icon/Cards2', Instruction = '打开后有几率获得若干张杏仙美人图', },
	{ TempleteID = 269.0, Name = '铁扇公主画卷', Icon = 'goods_icon/Cards2', Instruction = '打开后有几率获得若干张铁扇公主美人图', },
	{ TempleteID = 270.0, Name = '盘丝大仙画卷', Icon = 'goods_icon/Cards2', Instruction = '打开后有几率获得若干张盘丝大仙美人图', },
	{ TempleteID = 271.0, Name = '地涌夫人画卷', Icon = 'goods_icon/Cards2', Instruction = '打开后有几率获得若干张地涌夫人美人图', },
	{ TempleteID = 272.0, Name = '白骨夫人画卷', Icon = 'goods_icon/Cards2', Instruction = '打开后有几率获得若干张白骨夫人美人图', },
	{ TempleteID = 273.0, Name = '琵琶蝎子精画卷', Icon = 'goods_icon/Cards2', Instruction = '打开后有几率获得若干张琵琶蝎子精美人图', },
	{ TempleteID = 274.0, Name = '胡喜媚画卷', Icon = 'goods_icon/Cards2', Instruction = '打开后有几率获得若干张胡喜媚美人图', },
	{ TempleteID = 275.0, Name = '妲己画卷', Icon = 'goods_icon/Cards2', Instruction = '打开后有几率获得若干张妲己美人图', },
	{ TempleteID = 276.0, Name = '巨幅女儿国国王画卷', Icon = 'goods_icon/Cards3', Instruction = '打开后有几率获得多张女儿国国王美人图', },
	{ TempleteID = 277.0, Name = '巨幅玉兔画卷', Icon = 'goods_icon/Cards3', Instruction = '打开后有几率获得多张玉兔美人图', },
	{ TempleteID = 278.0, Name = '巨幅杏仙画卷', Icon = 'goods_icon/Cards3', Instruction = '打开后有几率获得多张杏仙美人图', },
	{ TempleteID = 279.0, Name = '巨幅铁扇公主画卷', Icon = 'goods_icon/Cards3', Instruction = '打开后有几率获得多张铁扇公主美人图', },
	{ TempleteID = 280.0, Name = '巨幅盘丝大仙画卷', Icon = 'goods_icon/Cards3', Instruction = '打开后有几率获得多张盘丝大仙美人图', },
	{ TempleteID = 281.0, Name = '巨幅地涌夫人画卷', Icon = 'goods_icon/Cards3', Instruction = '打开后有几率获得多张地涌夫人美人图', },
	{ TempleteID = 282.0, Name = '巨幅白骨夫人画卷', Icon = 'goods_icon/Cards3', Instruction = '打开后有几率获得多张白骨夫人美人图', },
	{ TempleteID = 283.0, Name = '巨幅琵琶蝎子精画卷', Icon = 'goods_icon/Cards3', Instruction = '打开后有几率获得多张琵琶蝎子精美人图', },
	{ TempleteID = 284.0, Name = '巨幅胡喜媚画卷', Icon = 'goods_icon/Cards3', Instruction = '打开后有几率获得多张胡喜媚美人图', },
	{ TempleteID = 285.0, Name = '巨幅妲己画卷', Icon = 'goods_icon/Cards3', Instruction = '打开后有几率获得多张妲己美人图', },
	{ TempleteID = 286.0, Name = '经书残页1', Icon = 'goods_icon/Cards1', Instruction = '经书残页1', },
	{ TempleteID = 287.0, Name = '经书残页2', Icon = 'goods_icon/Cards1', Instruction = '经书残页2', },
	{ TempleteID = 288.0, Name = '经书残页3', Icon = 'goods_icon/Cards1', Instruction = '经书残页3', },
	{ TempleteID = 289.0, Name = '经书残页4', Icon = 'goods_icon/Cards1', Instruction = '经书残页4', },
	{ TempleteID = 290.0, Name = '经书残页5', Icon = 'goods_icon/Cards1', Instruction = '经书残页5', },
	{ TempleteID = 291.0, Name = '经书残页6', Icon = 'goods_icon/Cards1', Instruction = '经书残页6', },
	{ TempleteID = 292.0, Name = '经书残页7', Icon = 'goods_icon/Cards1', Instruction = '经书残页7', },
	{ TempleteID = 293.0, Name = '经书残页8', Icon = 'goods_icon/Cards1', Instruction = '经书残页8', },
	{ TempleteID = 294.0, Name = '经书残页9', Icon = 'goods_icon/Cards1', Instruction = '经书残页9', },
	{ TempleteID = 295.0, Name = '经书残页10', Icon = 'goods_icon/Cards1', Instruction = '经书残页10', },
}
