--[[TableVIP.lua
--]]

TableVIP= 
{
	{ Ranking = 0.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 20.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 2.0, WineshopFast = 0.0, FamilyDonate = 1.0, ResetCopyTimes = 0.0, },
	{ Ranking = 1.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 60.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 3.0, WineshopFast = 0.0, FamilyDonate = 1.0, ResetCopyTimes = 0.0, },
	{ Ranking = 2.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 100.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 3.0, WineshopFast = 1.0, FamilyDonate = 1.0, ResetCopyTimes = 0.0, },
	{ Ranking = 3.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 200.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 4.0, WineshopFast = 1.0, FamilyDonate = 1.0, ResetCopyTimes = 0.0, },
	{ Ranking = 4.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 600.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 4.0, WineshopFast = 1.0, FamilyDonate = 2.0, ResetCopyTimes = 5.0, },
	{ Ranking = 5.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 1000.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 5.0, WineshopFast = 1.0, FamilyDonate = 2.0, ResetCopyTimes = 6.0, },
	{ Ranking = 6.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 1500.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 5.0, WineshopFast = 1.0, FamilyDonate = 2.0, ResetCopyTimes = 7.0, },
	{ Ranking = 7.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 2000.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 6.0, WineshopFast = 1.0, FamilyDonate = 2.0, ResetCopyTimes = 8.0, },
	{ Ranking = 8.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 3000.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 6.0, WineshopFast = 1.0, FamilyDonate = 2.0, ResetCopyTimes = 9.0, },
	{ Ranking = 9.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 4000.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 7.0, WineshopFast = 1.0, FamilyDonate = 2.0, ResetCopyTimes = 10.0, },
	{ Ranking = 10.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 5000.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 7.0, WineshopFast = 2.0, FamilyDonate = 2.0, ResetCopyTimes = 11.0, },
	{ Ranking = 11.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 6000.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 8.0, WineshopFast = 2.0, FamilyDonate = 2.0, ResetCopyTimes = 12.0, },
	{ Ranking = 12.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 7000.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 8.0, WineshopFast = 2.0, FamilyDonate = 2.0, ResetCopyTimes = 13.0, },
	{ Ranking = 13.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 8000.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 9.0, WineshopFast = 2.0, FamilyDonate = 3.0, ResetCopyTimes = 14.0, },
	{ Ranking = 14.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 9000.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 9.0, WineshopFast = 2.0, FamilyDonate = 3.0, ResetCopyTimes = 15.0, },
	{ Ranking = 15.0, Box = {{1.0,2000},{2,2000},{200001,1,4}}, RechargeNum = 0.0, Text = {{type = 2.0,title = "可以获得VIP1礼包",fontColor = cGreen},{type=1},
{type = 2,title = "体力购买次数增加到",fontColor = cWhite},{type = 2,title = "5",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite},{type=1},
{type = 2,title = "酒坊每天可以加速的次数增加至",fontColor = cWhite},{type = 2,title = "1",fontColor = cGreen},{type = 2,title = "次",fontColor = cWhite}}, BuyPowerNum = 10.0, WineshopFast = 2.0, FamilyDonate = 3.0, ResetCopyTimes = 16.0, },
}
