--[[TableTalks.lua
--]]

TableTalks= 
{
	{ ID = 1.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "你想说什么就说吧！"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 9.0, words = "我和你之间没啥好说的！"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "难道你不爱我了吗？"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 9.0, words = "你这狗皮膏药，我压根对你就一点意思都没有！"}
}, },
	{ ID = 2.0, },
	{ ID = 3.0, },
	{ ID = 4.0, },
	{ ID = 5.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "守护一族的勇士，我是三界神树之分身――小空。现在有一群不明身份的妖族正在围攻神树所在的青丘之国，情况危急，特来求援！"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "神树关系重大，不容有失。事不宜迟，咱们马上出发。"},
}, },
	{ ID = 6.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "守护勇士，我感受到了神树的召唤，现在我要把你传送进云中城。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "不是要去救神树啊？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "上路喽！"},
}, },
	{ ID = 7.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "这里就是三界夹缝的隐士城邦――云中城，树神命我先将勇士你安顿在这。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "带我来这里干嘛？神树危急解除了？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "勇士你有所不知，神树大人在三界、五行、六道、二十八层天中皆有分身，一般凡夫俗子不可能捕获神树真身。神树大人担心这背后有更大的阴谋，所以希望勇士您不要贸然行动。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "好吧，那我们现在做什么？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "工欲善其事，必先利其器。"},
}, },
	{ ID = 8.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "最新消息，又有一伙妖族集中在青丘之国外围，勇士大人你做好准备了么？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "随时可以出发。"},
}, },
	{ ID = 9.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "这些妖族应该是生活在狮驼岭附近的火毛族，他们跑这么远来围攻神树干嘛？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "果然是有很大的阴谋！"},
}, },
	{ ID = 10.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "小空，有没有办法把这些妖族一网打尽？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "没有办法，请勇士大人慢慢磨砺自己，逐个消灭他们。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "他们就不能有点专业精神，来个“总攻”什么的？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "正所谓【一沙一世界】，神树大人的分身众多，不同世界有不同的敌人，只能逐个消灭喽。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "好吧，那咱们休整一下，准备前往下个世界。"},
}, },
	{ ID = 11.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "这些家伙是来自黑风山的部族，他们大王已经皈依佛门了，他们为啥还要出来行凶呢？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "所以树神大人才说，这背后一定有很大的阴谋。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "神树大人这口风都是跟谁学的？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "狄大人和元芳啊！你不懂，这未来的事，你道行太浅，还看不到。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "……"},
}, },
	{ ID = 12.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "神树大人传来消息，已经发现这货妖族的首领，请勇士大人全副武装，上阵杀敌。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "太好了！请给我最好的装备。"},
}, },
	{ ID = 13.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "糟糕，传送被干扰了，这是一个充满陷阱的错误世界。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "无妨，这些陷阱拦不住我。"},
}, },
	{ ID = 14.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "平安返回，可喜可贺！"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "神树现在情况如何？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "不容乐观，请勇士大人尽快唤醒【战灵】，一同前往救援。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "战灵是何物？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "刚刚在错误空间内发现了一些战灵的神魂碎片，可以召唤出战灵协助战斗。"},
}, },
	{ ID = 15.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "勇士大人，战灵会协助您战斗，是非常强力的帮手。但它们也会死亡，当您回到云中城，它们才能重塑肉身。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "我知道了。"},
}, },
	{ ID = 16.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "黄风大王，没想到围攻神树的居然是你！"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 23.0, words = "那里来的毛头小妖，敢挡本大王的路，速速上来受死。"},
}, },
	{ ID = 17.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "黄风大王，我念你一身道行修炼不易，今天放你一条生路。速速离去，不可再犯。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 23.0, words = "技不如人，算我栽了。但小子，我告诉你，只要我黄风不死，必将再夺神树。咱们走着瞧！"},
}, },
	{ ID = 18.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "好奇怪，击败了黄风大王我感觉到体内有一股神奇的力量在蠢蠢欲动。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "快看看，获得了什么力量。"},
}, },
	{ ID = 19.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "奇怪，这里怎么那么多假和尚？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "都是旅游热惹的祸，现在妖怪都下海假扮和尚了。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "世态炎凉，还能不能脚踏实地做好妖怪这份有前途的职业了。"},
}, },
	{ ID = 20.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "我不明白，黄风大王究竟有什么目的要围攻神树，这对他并没有好处。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "关于这点，神树大人也在调查，或许其他的守护一族能知晓一些端倪。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "哦，那咱们回村，去问问长老。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "没有必要，在云中城与其他守护族人加为【好友】即可。"},
}, },
	{ ID = 21.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "所有神树的守护勇士，都可在自己的世界召唤其他守护勇士的力量协助自己，虽然只有一瞬间，但也是极强的助力。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "我明白了。"},
}, },
	{ ID = 22.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "狮驼岭、黑风山、黄风岭，山南海北的妖族都聚集过来了。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "神树大人分析说，它们的目标可能不是神树大人，而是其他什么人，围攻青丘之国只是声东击西。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "好可怕的势力……跟神树大人打个商量，咱们提前归降了吧。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "请不要放弃治疗。"},
}, },
	{ ID = 23.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "黄风大王，上次饶你一命，你居然不知悔改。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 23.0, words = "无需多言，自古成王败寇，咱们兵器底下见真章。"},
}, },
	{ ID = 24.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "你这是何苦，修行千年，白白葬送。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 23.0, words = "小子你不懂。我先是偷吃琉璃盏油，后囚禁神僧玄奘，被灵吉菩萨问罪之时我就永世不得翻身了。一招犯错，一生得道又有何用。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 23.0, words = "我们这些犯大过错的妖族想要翻身，就必须逆天改命，现在我们的计划就差这一步了，夺取神树，反攻人界。天亡不了我，等我重塑肉身，再与你大战300回合！哈哈哈……"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "他死了么？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "看样子是死了，但他说他能重塑肉身，难不成他能改写生死簿？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "死者为大，愿他在地府能真的安息吧。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "咱们先回云中城，我有不好的预感，他说的【反攻人界】一定不是什么好事。"},
}, },
	{ ID = 25.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "勇士大人请稍作休息，神树大人正在发动全部分身彻查这件事。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "有新消息一定要及时通知我。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "这段时间，勇士大人可以去【竞技场】，打法一下时间。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "那是什么地方？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "是神树大人专门开辟的竞技空间，所有守护一族可以在这个空间内互相训练，寻求突破。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "真是个好地方，在神树大人查明真相之前，我就在这打发一下时间。"},
}, },
	{ ID = 26.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "神树大人调查到黄风怪一行，是从人界出发围攻青丘之国的。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "从人界出发，这路真够远的。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "事出有妖，勇士大人准备好前往人界了么？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "随时可以出发，不过咱们的目的地是哪？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "大唐首府――长安城！"},
}, },
	{ ID = 27.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "这里就是长安城了。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "奇怪，我没看错的话，前面那群是妖族吧……"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "人界城市怎么会有那么多妖族？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "这长安城是被妖族占领了啊。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "此地不宜久留，逃命啊！"},
}, },
	{ ID = 28.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "妖族居然这么大规模入侵人界，之前怎么一点消息都没有？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "神树大人猜测这就是他们的声东击西之法，进攻人界才是他们的真正目的。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "进攻人界，必定会惊动西天如来佛祖，难道说……糟了，他们真正的目标是玄奘圣僧！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "那咱们马上前往长安城外的金山寺！"},
}, },
	{ ID = 29.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "玄奘圣僧应该还在金山寺内，事不宜迟，马上出发！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "寺内应该也有不少妖族，勇士大人要小心。"},
}, },
	{ ID = 30.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "玄奘圣僧，我们来救你了！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "贫僧在这里。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "圣僧，这里妖气太重，我无法调用神树的力量破开空间，咱们先出寺吧。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "阿弥陀佛，贫僧知道一条出寺的密道，两位请随我来。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "圣僧，我和小空非仙非人，你如此草率的就信任我们不妥吧？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "施主说笑了，贫僧三位徒弟皆是妖族，只要一心向佛，并没有什么不妥。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "的确如此，玄奘圣僧三位高徒神通广大，斗战圣佛更是勇猛无双。杀入金山寺的妖族虽然不弱，但绝无可能是他三人的对手，但这一路而上并未见到激战留下的痕迹，反倒整洁的像给我们准备的陷阱。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "阿弥陀佛，施主颇有慧根，贫僧只好送施主早登极乐，脱离苦海了！"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "圣僧是冒牌货！"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 35.0, words = "施主接招！"},
}, },
	{ ID = 31.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "说，真正的玄奘圣僧在哪？"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 35.0, words = "无可奉告……啊"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "什么人"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 31.0, words = "你是什么妖？在这做什么？"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 6.0, words = "大师兄，他应该就是保护神树的守护一族。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 31.0, words = "我知道，在我看来妖就是妖，就应该老老实实在妖界呆着，人界不是你们该来的地方。师弟，我继续追踪玄奘圣僧的踪迹，先走一步。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "他什么人啊？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "失礼了，在下玄天剑派天宗座下二弟子拜菊，刚刚那位是我师兄丹尘。我二人正在追踪玄奘圣僧的踪迹，正巧赶上刚才一幕。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "玄奘圣僧出什么事了？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "说来话长，现在三界大乱，妖族入侵，圣僧失踪，这一切都是一个叫邪心魔的妖族在背后策划的。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "他这样做有什么目的？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "暂不可知。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "各位，此地不宜久留，先随我回云中城吧。"},
}, },
	{ ID = 32.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "勇士，现在情况不容乐观。邪心魔是只不明真身的神秘妖族，拥有穿越时空的强大法力。圣僧的三位高徒，就是被他这手法术偷袭，现迷失在时空夹缝中。西天如来佛祖正带领诸位菩萨联合补下防护，稳定邪心魔已扰乱的时间。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "如来佛祖都没有办法么？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "千万年的时光布防何其困难，看来以后的事要靠自己了。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "可以确定邪心魔已经去了别的时间，并带走数量惊人的妖族军队。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "听你这么说，一定是有穿越时间的办法了吧。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "勇士你听说过【月光宝盒】么？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "听是听过，就是不知道盘丝大仙她老人家肯不肯出借。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "上门一问便知。"},
}, },
	{ ID = 33.0, Contents = {
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "这一路上都是邪心魔的党羽，盘丝大仙也有危险了。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "想必邪心魔也是知晓月光宝盒的神通，这一路凶多吉少。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "争分夺秒吧。"},
}, },
	{ ID = 34.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "大师兄已经先一步进入盘丝洞了，但洞内错综复杂，尚未见到盘丝大仙。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "进洞后咱们走你师兄的反方向，兴许运气好点。"},
}, },
	{ ID = 35.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "什么人在打斗？"},
     {posType = 1.0, roleType = 3.0, roleTempleteID = 29.0, words = "把月光宝盒交出来！"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 29.0, words = "想要宝盒自己来拿啊！"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "这怎么回事？"},
     {posType = 1.0, roleType = 3.0, roleTempleteID = 29.0, words = "来的正好，这个冒牌货偷袭本座洞府，还盗走了宝盒。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 29.0, words = "别颠倒是非，分明是你假扮本座想要取而代之！"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "分不出来，这怎么办？"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 31.0, words = "两个都是假的！先拿下有宝盒的！"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 29.0, words = "快走！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "大师兄不要追啊！哎……"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "这还一个呢，先搞定了再去追你师兄。"},
     {posType = 1.0, roleType = 3.0, roleTempleteID = 29.0, words = "痴心妄想！"},
}, },
	{ ID = 36.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "宝盒不在她身上，去追你师兄吧。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "希望师兄那边会有好消息。"},
}, },
	{ ID = 37.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "师兄，拿到月光宝盒了么？"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 31.0, words = "已交与宗主，宗主已先一步前往古代与妖族军队作战。咱们现在出发，与宗主汇合。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "速度出发吧。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 31.0, words = "你也要去？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "有什么问题？"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 31.0, words = "鄙人这生有七大恨，一恨大道不公，二恨祸事难平。三恨无德无行，四恨阴损小人。五恨未尝败果，六恨天下无敌。最恨与妖同世。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "……你是死心眼么？"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 31.0, words = "不与你做口舌之争，愿意自己跟过来，请便。"},
}, },
	{ ID = 38.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "这是到了那里？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "我感应一下……恩，应该是一千年前的花果山附近。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "咱们怎么跑这来了！？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "穿越时受到了一些小干扰，距离目的地偏差了三座山的距离。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "还真是小偏差"},
}, },
	{ ID = 39.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "没想到花果山附近的妖族也这么多。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "不是本土妖怪，都是邪心魔带过来的爪牙。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "一会到山脚下，咱们尽可能突围到内部。"},
}, },
	{ ID = 40.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "太好了，你们可算赶到了。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "有没有想我~"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "日思夜想，现在花果山的情况很不妙。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "发生什么了？不会水帘洞被毁了吧？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "还没有，但也不容乐观，咱们路上说。"},
}, },
	{ ID = 41.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "也就是说邪心魔穿越一千年，攻打花果山，就是为了在孙大圣诞生之前将仙石毁掉？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "没错，围攻花果山的兵力很强，仅凭咱们的人员是守不住的。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "所以说，咱们要通过一些【非同一般】的手段来阻止邪心魔？相信你已经有办法了吧。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "这个自然，现在想抵挡邪心魔的大军我们只能借兵，而且还需要一位实力足够强大的战将。这个年代符合以上条件，还能有可能帮咱们的只有一位妖怪――【牛魔王】。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "你确定牛魔王会帮咱们？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "不试试怎么知道。"},
}, },
	{ ID = 42.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "一会见到牛魔王知道想好怎么说服他了么？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "没想过。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "那怎么办？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "船到桥头自然直，走一步算一步吧。"},
}, },
	{ ID = 43.0, Contents = {
     {posType = 2.0, roleType = 3.0, roleTempleteID = 14.0, words = "尔等何人，为何闯我洞府，打伤我手下兵卒。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "实不相瞒，我等有要事禀报牛大王，但您手下兵卒不予通报，事关重大我等不得意只能硬闯，冒犯之处望请见谅。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 14.0, words = "我感觉到你们身上有神树的灵气，姑且不追究你们闯门之过。想找我谈事，没问题，但要有足够的实力。先赢过我的先锋，再谈其他。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "没问题。"},
}, },
	{ ID = 44.0, Contents = {
     {posType = 2.0, roleType = 3.0, roleTempleteID = 14.0, words = "尔等实力不俗，它败在你们手里不亏。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 6.0, words = "素闻牛大王武力超群，只可惜我们等实力平平，只敢挑战您的手下，不敢与您讨教一二。不过，在下知道一人，武功旷古烁今，法力无边，日后还会打上天庭，夺得【齐天】之称！"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 14.0, words = "世间还有此等人物，我怎么不知道？"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 6.0, words = "因为它尚未出生，出生之时惊天动地，众仙诸神无人不知，到时您与它意气相投结拜为兄弟……"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 14.0, words = "休得狂言，你有何道行，敢预知未来事。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 6.0, words = "我等本就是未来人，在我体内有西天如来佛祖留下的神念，您大可自行探知。千年之后，有一妖怪想要改写历史，弄的时空错乱。他现在正率领一只大军围攻花果山，为的就是消灭您尚未出生的义弟。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 14.0, words = "你体内确有如来佛祖的无边法力，但我不相信的你所说的。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 6.0, words = "牛大王，此事关系三界安危，对后世……"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 14.0, words = "它叫什么？你刚才说的围攻花果山，能穿越时空的妖怪叫什么？"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 6.0, words = "它，它自称邪心魔。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 14.0, words = "好，好。本王，四海有名称混世，西方大力号魔王。今日我遍会会他，看他是否三头六臂，有什么本事敢在我的眼皮底下妄动兵戈。小的们！抖擞精神，随本王出征！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "这就说服他了？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "可能他比较好说话吧……"},
}, },
	{ ID = 45.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "牛魔王的大军已经推进到花果山下，势如破竹，可喜可贺。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "但邪心魔一直没有露面。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "这个魔王非常神秘，行为飘忽不定，甚至没人知道他的真面目。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "那也要逼他出来，至少要知道玄奘圣僧的下落。"},
}, },
	{ ID = 46.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "这边的战场怎么一个人都没有？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "保持警惕，这么安静一定有猫腻。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "前面似乎有个小和尚，过去看看。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "小师傅，你在这里做什么？这周围都是妖族，你孤身一人很危险。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "贫僧正在为逝者超度。说道妖族，施主你不也是妖族？说道危险，贫僧敢问施主，何为危险？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "你这和尚好生奇怪，这兵荒马乱的自然危险，至于我们，我们是好心的妖族，不会加害于你，所以不危险啊。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "施主所言甚是，三界之内真正的大危险、大恐怖不外乎二字――【善恶】。孰为善，孰为恶，凡事因果必有源头，但二位刚才称自己为【好心的】妖族，已是将妖族归为恶方，这又是为何呢？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "你不是小和尚，你是妖怪变的！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "来来，你再看我是谁。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "你就算变成玄奘圣僧，也是骗不了我的。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "相貌不过一套臭皮囊，用也不是，舍也不是。哈哈，不疯不狂神似癫，时黑时白心已邪。痴人疯汉伪君子，辨我是佛还是仙？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "邪心魔！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "非也，我是玄奘，只不过世人认为我的心【邪】了，疯癫恐怖，所以又冠以【魔】字之名，故唤我为【邪心魔】。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "少说废话，快将真真的玄奘法师交出来！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "不信？不信也罢，世间万物凡有智慧者皆有邪心，不可避之，不可否之。故世间多事以无知之恶肆意屠戮他族，并称之为善。二位一心向善，但遭遇路人，却必须以口舌澄清，恐被误解为恶，实在荒谬。所以，在下今日要帮二位作【恶】，以问本心。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "我怎么没听懂他在说什么……"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "我虽然没听懂，但感觉好厉害的样子。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 14.0, words = "嗷……"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "你把牛魔王怎么了！？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "神树守护一族之勇士，你若击败牛魔王，我遍将玄奘交还与你。若不能，自然是做他斧下亡魂，好好选择吧。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 14.0, words = "嗷！"},
}, },
	{ ID = 47.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "邪心魔呢？牛魔王伤势很重，必须马上救治。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "消失了，这个混蛋居然控制牛魔王，情况危急我没能留手……"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "你搞错了，这个牛魔王是假的，真正的牛魔王确实被邪心魔重伤，现在玄奘圣僧正在照看他。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "假的！？等等，圣僧找到了？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "是，圣僧回来了，快随我去见他。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "咱们马上走。"},
}, },
	{ ID = 48.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "阿弥陀佛，贫僧见过诸位施主。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "圣僧有理了，不知道牛魔王伤势如何？应对如何医治？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "牛施主有法力护住元神，但肉体极近崩溃，贫僧只能延缓其消散之势，并不能医治。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "圣僧你都没有办法么？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "阿弥陀佛，出家人不打诳语，办法虽然有，但需要改变天理，不是贫僧不可为，而是不愿为。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "圣僧你有什么难处就说出来，我们帮忙。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "实不相瞒，想要救牛施主，就必须效仿我大徒弟，下地府改写生死簿，但这有违因果。而邪心，他恰恰希望我们如此。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "圣僧不必困扰，邪心魔已牛魔王性命逼迫我们去闹地府，但救人一命胜造七级浮屠，实为大善，相信佛祖会原谅我们的。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "阿弥陀佛，有劳各位了。"},
}, },
	{ ID = 49.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "阴曹地府地形太复杂，找了这么久也没找到生死簿的所在。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "生死簿应该是由判官保管，咱们直接去找判官拿，尽可能不要惊动阎王。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "如此甚好。"},
}, },
	{ ID = 50.0, Contents = {
     {posType = 2.0, roleType = 3.0, roleTempleteID = 20.0, words = "什么人，敢擅闯地府！"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "好人，想借您生死簿一用，我们着急救人。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 20.0, words = "狂妄！生死簿岂是你说借就借，说改就改的！"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "不好意思，那我们只能得罪了。"},
}, },
	{ ID = 51.0, Contents = {
     {posType = 2.0, roleType = 3.0, roleTempleteID = 20.0, words = "哼！就算你们拿走了生死簿，没有阎王令你们也休想修改上面一笔一划。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "原来如此，看来我们还要去拜访一下阎王。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 20.0, words = "准备面对十殿阎罗的怒火吧！"},
}, },
	{ ID = 52.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "守勇士大人，咱们需要快点，牛魔王可能坚持不了多久了。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "即刻出发，见到阎王，改写生死簿。"},
}, },
	{ ID = 53.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "这里已经是地府的最深处了，为何不见阎王的身影。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 47.0, words = "哦？你找本王何事？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "劳烦阎王现出真身，我等想借阎王令一用。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 47.0, words = "看来就是你们从判官手上抢夺了生死簿。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "实乃事出有因，我等不得意才……"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 47.0, words = "不必多说，我执掌阴间数百载，凡闯地府者，都是为了救魂复命，但天命中自有劫数，人鬼殊途。尔等要逆天改命，先能看能不能过我这关。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "那就得罪了！"},
}, },
	{ ID = 54.0, Contents = {
     {posType = 2.0, roleType = 3.0, roleTempleteID = 47.0, words = "尔等已经修改了牛魔王的命数，不要再在地府逗留，速速离去。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "多谢阎王救牛魔王一命。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 47.0, words = "尔等篡改生死簿有违天道，必将铸成大错。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "阎王大人如此慷慨，不如这阎王令也借贫僧一用如何？"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "糟了，阎王令消失了。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "诸位有所不知，这阎王令除了可以改写生死簿外，更重要的能力是号令地府十万阴兵。我军有此阵容，实乃如虎添翼。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "邪心魔今日你休想踏出这里一步。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "施主，你救一牛魔王，送我十万阴兵，是善是恶？今日你是想留我，也留不得。若是有缘，你我朝歌再见。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "糟了他又穿越时空了。"},
}, },
	{ ID = 55.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "已经查明了，邪心魔回到了商周交替之际，并率领十万阴兵加入了纣王一方。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "如果周武王输了，那历史改变中原实则落入了妲己为首的一帮妖族手中，难道这才是邪心魔的真正目的？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "不管是不是，我们现在必须穿越回去，协助武王伐纣。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "希望这次穿越不要失误了。"},
}, },
	{ ID = 56.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "小空，咱们现在在哪？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "朝哥城附近吧……"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "所以咱们又偏离目的地了？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "这次不是干扰，像是有人故意引导咱们过来的。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "邪心魔……朝歌城再会是么。"},
}, },
	{ ID = 57.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "朝歌城似乎要有什么大事发生，现在妖怪这么多，很难混进去啊。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "这么多妖怪才好混进去呢，互相都不认识。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "无所谓了，先找到其他人再说吧。"},
}, },
	{ ID = 58.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "中间那个东西貌似就是传说中的炮烙柱啊。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "上面有人，速度救下来。"},
}, },
	{ ID = 59.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "快看看救下谁了。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "尔等助手！快把人放了！"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "你搞错啦！我们也是救人的！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "你们也是来救人的？太师怎么没跟我说过。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "你是雷震子，那我救下来这位就是……"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "正是西伯昌之子――【姬发】"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "他是周武王！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "什么？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "你不懂，这未来的事，你道行太浅，还看不到。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "这是我的台词。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "事不宜迟，咱们赶紧带着公子离开这。"},
}, },
	{ ID = 60.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "再往前走就是岐山境内，咱们就算安全了。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 7.0, words = "雷震子，老朽在这恭候你与公子多日了。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "拜见太师，末将幸不辱命，将公子带回。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 7.0, words = "回来就好，这位想必就是神树勇士了吧。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "拜见太师，说话太师您知道我？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "我们早就到了，已经和姜太师说了邪心魔的事情，现在太师已经答应我们共同对抗邪心魔。"}, 
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "那太好了。"},
}, },
	{ ID = 61.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "太师您有事找我？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 7.0, words = "是的，现在我军与商军激战正酣，邪心魔又率领十万阴兵助阵，情况不容乐观，老夫希望勇士你能加入军队，削弱商军的力量。"}, 
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "太师客气了，这是在下义不容辞的事。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 7.0, words = "有劳了"}, 
}, },
	{ ID = 62.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "勇士，今天咱们要去突袭商军的后方，里面镇守着一只上古猛兽。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "无妨，打不过还可以逃啊。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "……您这战术真是随意。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "没事，我打不过不还有你么，要不你先上，我看你不行了，再上。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "咱们还是出发吧。"},
}, },
	{ ID = 63.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "玄奘圣僧到了。"}, 
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "圣僧你怎么来了。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "其实贫僧早就到了，之前与姜太师商议共同部下八门奇阵，以压制邪心魔的十万阴兵。"}, 
     {posType = 2.0, roleType = 2.0, roleTempleteID = 7.0, words = "正是，现在只有我二人合力施法，才有可能压制牧野的阴兵大军，让我军与商军正面决战。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "那太好了，我需要做什么。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 7.0, words = "勇士你需要独自潜入朝歌城，打通通向瓮城之道路。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "到时咱们里应外合，就能拿下朝歌城。"},
}, },
	{ ID = 64.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "如果我没看错，那边捎首弄姿的那位一定就是妲己了吧。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "没错！"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "长得一般啊，不像传言中那般妖媚。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "可能古时候审美不一样吧。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 21.0, words = "住口！当老娘没听到啊！"},
}, },
	{ ID = 65.0, Contents = {
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "糟糕让她逃了！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 6.0, words = "我与大师兄去追！"},
     {posType = 1.0, roleType = 3.0, roleTempleteID = 31.0, words = "跟上！"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "他们追去了。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "他二人应该没问题，咱们先回去待命吧。"},
}, },
	{ ID = 66.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 7.0, words = "我军与商军会战于牧野，激战正酣，汝等速度前去助阵，追击敌寇。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "得令。"},
}, },
	{ ID = 67.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "捷报！我军大胜！"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "这就赢了？妲己呢？纣王呢？"}, 
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "妲己下落不明，正在搜捕。纣王已自焚于鹿台之上。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "邪心魔依旧没有现身。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "务须担心，现在大事已定，他们再无翻身之日。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "希望如此。"},
}, },
	{ ID = 68.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 8.0, words = "勇士，太公有令，今日午时三刻在封神台举行封神大典。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "好的，我知道了。"}, 
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "封神大典啊！这可是历史性的一刻！"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "我总觉得这事有蹊跷，咱们还是要保持警惕。"},
}, },
	{ ID = 69.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 7.0, words = "吉时已到，封神大典即刻开始。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 6.0, words = "太公且慢！封神榜已被妲己调换了，这是个陷阱啊。"}, 
     {posType = 2.0, roleType = 2.0, roleTempleteID = 7.0, words = "此话当真？速速上台来。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 6.0, words = "是太公……今日就是你的死期！"}, 
     {posType = 2.0, roleType = 2.0, roleTempleteID = 7.0, words = "妲己！这等孩童幻术怎能欺骗老夫的双眼。"},
     {posType = 1.0, roleType = 3.0, roleTempleteID = 21.0, words = "姜子牙，你觉得你能困住老娘么。"}, 
     {posType = 2.0, roleType = 2.0, roleTempleteID = 7.0, words = "休得猖狂，整个封神台已被玄奘法师的经文所护，今日你妲己插翅难飞。"},
     {posType = 1.0, roleType = 3.0, roleTempleteID = 21.0, words = "你们今天都要给老娘陪葬！"}, 
}, },
	{ ID = 70.0, Contents = {
     {posType = 1.0, roleType = 3.0, roleTempleteID = 21.0, words = "大王救我……大王救我啊。"}, 
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "人死如灯灭，妖也一样，这尘世容不下你，下辈子做个不用勾心斗角的小狐狸吧。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "邪心魔你终于肯露面了。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "不是不见，缘分未到。贫僧这不是出现了么。"}, 
     {posType = 1.0, roleType = 2.0, roleTempleteID = 10.0, words = "邪心，收手吧。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "法师，你动摇了？"}, 
     {posType = 1.0, roleType = 2.0, roleTempleteID = 10.0, words = "本心未动，只是不愿见到生灵涂炭。无论时空如何变化，仍要以向善之心见众生。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "虎狼捕羊，禽鸟食鱼，万物生得自然，唯有妖魔食人以为恶，何解。凡尘千百年视妖为错，视魔为恶。若众生皆向善，唯有天下无魔。"}, 
     {posType = 1.0, roleType = 2.0, roleTempleteID = 10.0, words = "生灵无可逃罪业，贫僧求取大乘圣经，望借圣经见本心，苍生可轻罪业。苦海无涯，回头是岸。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "但生灵多愚钝，法师可视妖为友，他人却不行。世人容不下妖，乃天道有疾，已入骨髓，需刮骨去腐，逆天而行。人不容妖，妖为何要适人而活。这封神榜借我一用，让我去完成大业如何。"}, 
     {posType = 1.0, roleType = 2.0, roleTempleteID = 7.0, words = "魔王，你休想……啊啊啊！"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "丹尘，怎会是你！"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 31.0, words = "封神榜到手了，咱们走吧。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "法师，你我洪荒初始再见，这天道我是改定了。"}, 
     {posType = 1.0, roleType = 2.0, roleTempleteID = 10.0, words = "邪心，时空变化只是表象，万物之心从未变过。"}, 
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "他们又穿越了……勇士，这故事我怎么看不懂了。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "看不懂就对，咱们快追上他们。"},
}, },
	{ ID = 71.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "这邪心魔又躲起来了，连他手下的妖怪也都躲起来了。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "他这叫按兵不动，这洪荒世界上古山妖众多，他也要避其锋芒。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "而且这里的妖魔还四处捕捉人类，勇士咱们顺道就把人救下吧。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "这个自然。"},
}, },
	{ ID = 72.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "这一路的上古妖魔真是难缠，好在咱们把他们打退了，还顺便救下了一些人类。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "我有不好的感觉，刚才被妖魔带走的其他人类，似乎有大人物。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "我听其他人说，似乎是叫什么【轩辕】族长的。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "【轩辕】！糟了，出大事了，速速返回云中城。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "这就走。"},
}, },
	{ ID = 73.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "查清楚了，囚禁轩辕黄帝正是魔王蚩尤。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "历史上轩辕与蚩尤是死敌，现在黄帝被俘，蚩尤迟迟没有痛下杀手，这其中有诈啊。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "若贫僧猜的不错，当是邪心授意他如此行事。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "圣僧，邪心魔如此大费周章，所下众多诸多阴谋，所为何事？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "实不相瞒，邪心认为天道有疾，世间常理多有病态，想要改天革世。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "圣僧，您似乎一直想要感化邪心魔，是这样么？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "阿弥陀佛。施主与小神树使，静听贫僧一言。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "人间以妖为镜，有因结果，有善缘亦有罪业。人世间有玄奘，妖族亦有邪心魔。贫僧求取真经，望教戒众生因果循环求本心以向善。而邪心则改天革世，唯求众生平等，再无人妖仙魔之分。可惜，他此举嗔戾暴力，以为世理所不容。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 1.0, words = "这么说，邪心魔其实还不坏……是这样么？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 10.0, words = "他尚未顿悟。在佛眼中，本就无人妖仙魔之分，皆是众生，是万物。罪业无论出身宗族，皆为因果。时空变幻，物是人非，但佛不会变，因果不会变。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "圣僧，弟子似乎明白了。当务之急还是要阻止邪心魔的下一步行动，圣僧这些话，我会带给他的。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "哎？勇士你明白了，我怎么听不懂呢……哎，等等我。"},
}, },
	{ ID = 74.0, Contents = {
     {posType = 2.0, roleType = 3.0, roleTempleteID = 44.0, words = "那里来的家伙，敢阻挡本座。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "魔王蚩尤，速速释放所有人类。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 44.0, words = "小子找死！"},
}, },
	{ ID = 75.0, Contents = {
     {posType = 2.0, roleType = 3.0, roleTempleteID = 44.0, words = "不可能，我不会失败！我是最强的魔王！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "不好他要逃。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "顾不上了，先救人要紧。"},
}, },
	{ ID = 76.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "虽然救出了众人，但上古神器轩辕剑还是遗失了。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "不用想，九成九在邪心魔手里。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "西北天有滔天魔气，估计是逃走的蚩尤吧。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "战胜蚩尤，邪心魔在这个世界也不剩其他帮手了，咱们出发吧。"},
}, },
	{ ID = 77.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "好强的魔气，他应当是吞噬了不少魔兵。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 44.0, words = "现在的我！无法阻挡！"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "多行不义必自毙，老魔王今天就是你的死期。"},
}, },
	{ ID = 78.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "邪心魔！蚩尤败了，轩辕剑也从他身上找出来了，你还不现身吗！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "施主愚钝了，贫僧要轩辕剑何用？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "什么？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "贫僧要的，是蚩尤这万恶滔天的魔气。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 10.0, words = "邪心，痴念太深。心生则种种法生，心灭则种种法灭。你表象心生，实早已心灭，心灭则心不净，不净则见混沌错当见佛土。你若再向前，则是苦海无疆，徒生悲凉。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "法师，诚如所言，邪心早以心灭。可惜天道有疾不除万妖皆心灭，我为魔则天下无魔，岂不快哉？法师无需再劝，万物无可逃因果，罪业报应自会阻我。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "邪心魔，无论你逃到哪里，我都会追上去阻止你。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "我已凑齐三界诸神之法力，现在就能创造一个只有妖魔存在的世界。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "你要干什么？"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 48.0, words = "诸位，本座大事已成。若有缘，咱们幻境相见。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 10.0, words = "邪心，凡事太尽，缘分势必早尽。你如此耗费三界灵气，一旦诸界崩塌，万物将会归于混沌。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 48.0, words = "法师，本座有一事相问。若你为一届凡人，没有大圣、天棚等人护送，西天之路遥远崎岖，还有盗匪灾祸，远超九九八十一难，你还会去西天求取真经么？"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 10.0, words = "时空变幻，唯佛不变。生灵万物需轻罪业以见善心，贫僧定会去求真经。无论十载还是二十载，师徒四人或是只有贫僧一人，贫僧都会去西天求取真经。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 48.0, words = "阿弥陀佛……"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "就让他这么走了？"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "不，只是换个地方消灭它而已。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "欲知后事如何，且看下回分解！"},
}, },
	{ ID = 79.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "你要找午夜惊魂？。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "是啊"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 1.0, words = "晚上多打打副本就会遇见啦！"},
}, },
	{ ID = 80.0, Contents = {
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "以命相搏，导致真经散落世间，还废掉本座不少修为，算是不错了。不过，留你不得……"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 10.0, words = "切莫杀生，你的目标是贫僧，贫僧与你走便是。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "法师，你搞错了，本座的目的是佛祖亲传的五千卷经文，现在经书化为经文散落世间，有不少还破开空间，流进了过去的时空。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 10.0, words = "这件事贫僧有不可推卸的责任，无不管是否再行十万八千里，贫僧也会寻回全部经文。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "本座也有此意，法师与本座同行可好。"},
     {posType = 1.0, roleType = 2.0, roleTempleteID = 10.0, words = "若你不再杀生，贫僧同行便是。现在，也请你放过这位施主。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "无所谓，法师咱们上路吧。"},
}, },
	{ ID = 81.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "在下乃是三界神树坐下护卫一族，今日应邀特来拜见玄奘法师。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "这位施主，法师每日忙于翻译经文，谢绝见客。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "那就奇怪了，法师邀请三界有识之士前来，共享真经抄本，这是三界众所周知的。法师繁忙，可能遗忘此事，劳烦小师傅再为通报。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "这……施主随我来吧，但请施主在藏经阁外稍后。"},
}, },
	{ ID = 82.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "小师傅，你们这偌大的金山寺，怎么人那么少啊？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "众僧都在外化缘，并未在寺内。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "果然啊，僧人不在寺内，这佛家圣地都生出一股妖气了。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "哼哼……你察觉了又如何"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "何方妖孽，还不现出原型。"},
     {posType = 2.0, roleType = 3.0, roleTempleteID = 77, words = "拦住他！"},
}, },
	{ ID = 83.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "你是何人？玄奘法师在哪里？"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "贫僧就是玄奘啊。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "妖魔，速速将玄奘法师还来。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "哼哼……你察觉了又如何"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "何方妖孽，还不现出原型。"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "看你有没有这个本事了。。"},
}, },
	{ ID = 84.0, Contents = {
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "妖魔，再给你个机会，将法师还来！"},
     {posType = 2.0, roleType = 2.0, roleTempleteID = 9.0, words = "非也，贫僧给施主个机会，速速退去。"},
     {posType = 1.0, roleType = 1.0, roleTempleteID = 1.0, words = "妖魔接招！"},
}, },
}
