--[[TableQuestions.lua
--]]

TableQuestions= 
{
	{ ID = 1.0, Question = '《百家姓》中“赵钱孙李”的下一句是?', CorrectOption = 2.0, Option = {'冯陈楚卫.','周吴郑王.','蒋沈韩杨.','不知道.'}, },
	{ ID = 2.0, Question = '《大唐玄奘》的主人公是谁？', CorrectOption = 4.0, Option = {'孙悟空.','猪八戒.','沙和尚.','唐僧.'}, },
	{ ID = 3.0, Question = '金庸的小说《射雕英雄传》里，郭靖被铁木真封为什么驸马? ', CorrectOption = 1.0, Option = {'金刀驸马.','铁刀驸马.','银刀驸马.','不知道.'}, },
	{ ID = 4.0, Question = '金庸的小说《笑傲江湖》里，辟邪剑法是谁家的? ', CorrectOption = 1.0, Option = {'林平之.','令狐冲.','岳不群.','任我行.'}, },
	{ ID = 5.0, Question = '《大唐玄奘》电影中玄奘的扮演者是谁？', CorrectOption = 1.0, Option = {'黄晓明.','任泉.','李易峰.','韦小宝.'}, },
	{ ID = 6.0, Question = '《大唐玄奘》电影的导演是谁？', CorrectOption = 1.0, Option = {'王家卫.','李安.','冯小刚.','张纪中.'}, },
	{ ID = 7.0, Question = '“MP3”是电脑中哪种文件常用的格式名? ', CorrectOption = 3.0, Option = {'视频.','图片.','音频.','不知道.'}, },
	{ ID = 8.0, Question = '张纪中版《鹿鼎记》中韦小宝的扮演之是谁？', CorrectOption = 3.0, Option = {'陈小春.','张卫健.','黄晓明.','周星驰.'}, },
	{ ID = 9.0, Question = '游戏中，寻宝npc是哪一位？', CorrectOption = 1.0, Option = {'胖老头.','猫猫喵.','小恋佳.','小空.'}, },
	{ ID = 10.0, Question = '冬瓜、黄瓜、西瓜、南瓜都能吃，什么瓜不能吃？', CorrectOption = 3.0, Option = {'木瓜.','地瓜.','傻瓜.','北瓜.'}, },
	{ ID = 12.0, Question = 'A和C谁比较高呢?', CorrectOption = 1.0, Option = {'C.','A.','B.','D.'}, },
	{ ID = 13.0, Question = '橡皮、老虎皮、狮子皮哪一个最不好?', CorrectOption = 4.0, Option = {'老虎皮.','狮子皮.','不知道.','橡皮.'}, },
	{ ID = 14.0, Question = '阿拉丁的爸爸的哥哥是谁？', CorrectOption = 2.0, Option = {'帕拉丁.','阿拉伯.','不知道.','哈哈.'}, },
	{ ID = 15.0, Question = '0到9这几个数字谁比较高？', CorrectOption = 1.0, Option = {'0.','9.','1.','5.'}, },
	{ ID = 16.0, Question = '《大唐玄奘》中的西域美女是谁？', CorrectOption = 3.0, Option = {'杨幂.','杨颖.','楼佳悦.','范冰冰.'}, },
	{ ID = 17.0, Question = '话梅，杨梅，草莓谁的打扮最不好看？', CorrectOption = 2.0, Option = {'话梅.','杨梅.','草莓.','都好看.'}, },
	{ ID = 18.0, Question = '夕阳西下，断肠人在哪里?', CorrectOption = 2.0, Option = {'天涯.','医院.','家.'}, },
	{ ID = 19.0, Question = '上课老师抽查背课文，小猪、小狗、小猫都举手了，老师会叫谁?', CorrectOption = 2.0, Option = {'小猪.','小狗.','小猫.'}, },
	{ ID = 20.0, Question = '糖、醋、油、盐谁的工作量最少?', CorrectOption = 4.0, Option = {'糖.','醋.','油.','盐.'}, },
	{ ID = 21.0, Question = '《大唐玄奘》的主要拍摄地点是哪里？', CorrectOption = 1.0, Option = {'敦煌.','新疆.','塔里木.','吐鲁番.'}, },
	{ ID = 22.0, Question = '游戏中，好友之间赠送礼物可提升什么？', CorrectOption = 1.0, Option = {'亲密度.','战斗力.','等级.'}, },
	{ ID = 23.0, Question = '某人花19块钱买了个玩具，20块钱卖出去。他觉得不划算，又花21块钱买进，22块钱卖出去。请问它赚了多少钱？', CorrectOption = 2.0, Option = {'1元.','2元.','3元.','4元.'}, },
	{ ID = 24.0, Question = '一双鞋卖16元，一只鞋卖多少钱？', CorrectOption = 3.0, Option = {'8元.','4元.','不卖.'}, },
	{ ID = 25.0, Question = '一条小船要渡３７人，一次只能有７人，几次能渡完？', CorrectOption = 2.0, Option = {'5.','6.','7.','8.'}, },
	{ ID = 26.0, Question = '用椰子和西瓜打头哪一个比较痛', CorrectOption = 3.0, Option = {'椰子.','西瓜.','头.'}, },
	{ ID = 27.0, Question = '三个金“鑫”，三个水叫“淼”，三个人叫“众”，那么三个鬼应该叫什么?', CorrectOption = 2.0, Option = {'鬼.','救命.','逃.','不知道.'}, },
	{ ID = 28.0, Question = '‘春花秋月何时了，往事知多少’是哪位诗人的名句？', CorrectOption = 4.0, Option = {'李白.','杜甫.','白居易.','李煜.'}, },
	{ ID = 29.0, Question = '《鹿鼎记》中，韦小宝一共有多少个老婆？', CorrectOption = 1.0, Option = {'7.','8.','9.','6.'}, },
	{ ID = 30.0, Question = '坦克是哪个国家发明的？', CorrectOption = 4.0, Option = {'中国.','俄国.','美国.','英国.'}, },
	{ ID = 31.0, Question = '“垂帘听政”始于何时？', CorrectOption = 3.0, Option = {'宋朝.','元朝.','唐朝.','清朝.'}, },
	{ ID = 32.0, Question = '《指环王》中的指环可以让人？', CorrectOption = 2.0, Option = {'不死.','隐身.','施展魔法.'}, },
	{ ID = 33.0, Question = '“一衣带水”的水是指哪条河流？', CorrectOption = 1.0, Option = {'长江.','黄河.','珠江.','黑龙江.'}, },
	{ ID = 34.0, Question = '西游记中去西天取经的“唐三藏”的真名是？', CorrectOption = 1.0, Option = {'玄奘.','三藏.','江流.'}, },
	{ ID = 35.0, Question = '卯时相当于几点？', CorrectOption = 1.0, Option = {'5－7点.','7－9点.','9－11点.','3－5点.'}, },
	{ ID = 36.0, Question = '戛纳电影节在哪国举办？', CorrectOption = 2.0, Option = {'美国.','法国.','中国.','英国.'}, },
	{ ID = 37.0, Question = '被称为“第七艺术”的是？', CorrectOption = 3.0, Option = {'歌剧.','话剧.','电影.'}, },
	{ ID = 38.0, Question = '被称为中国古代第一个监狱的凌里城位于现在的？', CorrectOption = 1.0, Option = {'安阳.','甘肃.','青岛.','上海.'}, },
	{ ID = 39.0, Question = '中国古代名医华佗为谁所杀？', CorrectOption = 1.0, Option = {'曹操.','孙权.','刘备.','周瑜.'}, },
	{ ID = 40.0, Question = '“月上柳梢头，人约黄昏后”描写的是哪个传统节日？', CorrectOption = 2.0, Option = {'中秋.','元宵.','端午.','七夕.'}, },
	{ ID = 41.0, Question = '下列哪个成语典故与项羽有关？', CorrectOption = 3.0, Option = {'隔岸观火.','暗度陈仓.','破釜沉舟.','背水一战.'}, },
	{ ID = 42.0, Question = '梨园用来指代戏曲界，那么“杏林”指代的是？', CorrectOption = 1.0, Option = {'医学界.','教育界.','不知道.'}, },
	{ ID = 43.0, Question = '“金戈铁马，气吞万里如虎“是谁的词句？', CorrectOption = 2.0, Option = {'岳飞.','辛弃疾.','李商隐.','杜甫.'}, },
	{ ID = 44.0, Question = '明朝永乐年间，从西洋归来的郑和船队带回了一只西方异域兽“麒麟”，就是现在我们所知的？', CorrectOption = 3.0, Option = {'狮子.','老虎.','长颈鹿.','豹子.'}, },
	{ ID = 45.0, Question = '“变脸”是哪个剧种的绝活？', CorrectOption = 4.0, Option = {'京剧.','评剧.','越剧.','川剧.'}, },
	{ ID = 46.0, Question = '"山城"是我国哪座城市的雅号 ?', CorrectOption = 3.0, Option = {'洛阳.','西安.','重庆.','福州.'}, },
	{ ID = 47.0, Question = '我国最大的佛像是哪一座 ?', CorrectOption = 4.0, Option = {'潼南金佛.','屏山大佛.','荣成大佛.','乐山大佛.'}, },
	{ ID = 48.0, Question = '我国抗日战争期间八路军的总指挥是？', CorrectOption = 3.0, Option = {'毛泽东.','周恩来.','朱德.','彭德怀.'}, },
	{ ID = 49.0, Question = '游戏中，好友系统是多少级开启的？', CorrectOption = 4.0, Option = {'1级.','5级.','3级.','9级.'}, },
}
