--===================================================
-- (c) copyright 2014 - 2015, www.cfanim.cn
-- All Rights Reserved.
--==================================================
-- filename:  globals.lua
-- author:    taoye
-- e-mail:    553681974@qq.com
-- created:   2014/12/7
-- descrip:   全局包含
--===================================================

-- 网络模块
require("NetRequirs")

-- 数据表
require("TableBoxAndCards")
require("TableBuff")
require("TableChallengeCopys")
require("TableChallengeCopysMaps")
require("TableConstants")
require("TableCumulateRecharge")
require("TableEntitys")
require("TableEntitysSkills")
require("TableEquips")
require("TableFailGuide")
require("TableFairyLand")
require("TableFairyLandDan")
require("TableFairyLandDanLevel")
require("TableFamilyDonate")
require("TableFamilyEvents")
require("TableFamilyLab")
require("TableFamilyLevel")
require("TableFamilyPosition")
require("TableFamilyShop")
require("TableFamilyTech")
require("TableTaskFamily")
require("TableFriendSkills")
require("TableGetGold")
require("TableGoldCopys")
require("TableGoldCopysMaps")
require("TableGuideStory")
require("TableGuideStoryTalk")
require("TableHomeBuff")
require("TableIBeauties")
require("TableIBeautiesGroup")
require("TableIBladeSoul")
require("TableIBladeSoulPr")
require("TableItems")
require("TableLevel")
require("TableMainUIFunc")
require("TableMainActivityFunc")
require("TableMapBossCopys")
require("TableMapBossCopysMaps")
require("TableMarqueeMessge")
require("TableMazeCopys")
require("TableMazeCopysMaps")
require("TableMidNightChapter")
require("TableMidNightCopys")
require("TableMidNightCopysMaps")
require("TableMonster")
require("TableMonsterSkills")
require("TableNetError")
require("TableNewFuncOp")
require("TableNewFunction")
require("TableNewbie")
require("TableNpcRolesOnWorldMap")
require("TableQuestions")
require("TableOperateQueues")
require("TableTaskBounty")
require("TableTaskDaily")
require("TableTaskMain")
require("TableTaskSub")
require("TableTaskVitality")
require("TablePlayerRoles")
require("TablePets")
require("TablePetsLevel")
require("TablePetsSkills")
require("TablePoker")
require("TableRolePassiveSkills")
require("TableRoleSkills")
require("TableRoleTalent")
require("TableStones")
require("TableStoryChapter")
require("TableStoryCopys")
require("TableStoryCopysMaps")
require("TableStuffCopys")
require("TableStuffCopysMaps")
require("TableCJG")
require("TableRoleSkillsTree")
require("TableBuyCopyTimes")
require("TableActivity")
require("TablePetsResonance")
require("TableMonthSign")
require("TableLevelGift")
require("TableFirstRecharge")
require("TableSubActivityFunc")
require("TableGivePowerNum")
--require("TableFollowupbie")
require("TableTalks")
require("TableTeamAIFightCopys")
require("TableTeamAIFightCopysMaps")
require("TableTowerChapter")
require("TableTowerCopys")
require("TableTowerCopysMaps")
require("TableTriggers")
require("TablePVPCopysMaps")
require("TableInspire")
require("TableHuaShanCopysMaps")
require("TableHelpText")
require("TableArena")
require("TableWineshop")
require("TableFamilyPosition")
require("TableVIP")
require("TableAdvertiseMent")
require("TableOnlineRewards")
require("TableRank")
-- 模板表
require("TableTempleteEntitys")
require("TableTempleteEquips")
require("TableTempleteItems")
require("TableTempleteNpcRoles")
require("TableTempleteCareers")
require("TableTempletePets")
require("TableTempleteMonster")
require("TableTempleteSkills")
require("TableTempleteAttackLevelDiff")
require("TableTempleteBeauties")

-- 管理器单例
-- util
require("UserManager")
require("ResPlistManager")
require("AudioManager")
-- com
require("BagCommonManager")
require("BeautyManager")
require("BuffManager")
require("EmailManager")
require("FinanceManager")
require("GemManager")
require("ArenaManager")
require("FamilyManager")
require("SturaLibraryManager")
require("ActivityManager")
-- core
require("StagesManager")
require("BattleManager")
require("AIManager")
require("SkillsManager")
require("EntitysManager")
require("MapManager")
require("RectsManager")
require("RolesManager")
require("PetsManager")
require("FriendManager")
require("MonstersManager")
require("TriggersManager")
require("TalksManager")
require("NoticeManager")
require("LayerManager")
require("DialogManager")
require("NewbieManager")
require("OptionManager")
-- login
require("LoginManager")
-- task
require("PurposeManager")
require("TasksManager")
require("CDManager")
require("ChatManager")
require("StoryGuideManager")

